### ISSUE TITLE
WS2016.3 support

### ISSUE THREAD

**Issue by anstarovoyt** [Turbo87/intellij-emberjs#104]
Hi! WS2016.3 is out and we need a compatible plugin version for it

**Comment by Turbo87** [comment]
I just published [v2016.3.1](https://plugins.jetbrains.com/update/index?pr=&updateId=30266), thanks for the hint!

**Comment by anstarovoyt** [comment]
it was fast, thank you!

**Comment by Turbo87** [comment]
I had prepared for that already in https://github.com/Turbo87/intellij-emberjs/pull/101, just hadn't put out the release yet 😉
