### ISSUE TITLE
Plugin 'Ember.js' is incompatible with this installation

### ISSUE THREAD

**Issue by danr1979** [Turbo87/intellij-emberjs#106]
Hi.

I have just purchased the latest version of PHP Storm (2016.2.2) and have tried installing your plugin for my Ember development but I get the error in the title of this issue.  Will your plugin eventually be compatible with this version of the IDE or is there a way around this error please?

Many thanks.

**Comment by Turbo87** [comment]
how did you try to install it? did you follow the instructions [here](https://github.com/Turbo87/intellij-emberjs#installation)?

[intellij-emberjs v2016.2.6](https://github.com/Turbo87/intellij-emberjs/releases/tag/v2016.2.6) is the latest version that is compatible with PHP Storm v2016.2.2 and in theory that is what should be offered to you if you install the plugin through the [JetBrains Plugin Repository](https://plugins.jetbrains.com/plugin/8049).

**Comment by danr1979** [comment]
Ah apologies, I simply downloaded the zip & pointed to it in PHP Storm. I'll do it from the Jetbrains repository instead.

Thanks.
