### ISSUE TITLE
Accessing "class name" from live templates with pods

### ISSUE THREAD

**Issue by Ramblurr** [Turbo87/intellij-emberjs#107]
I'm trying to create some helpful live templates that need to reference the name of the open "class".

By this I mean if I am editing `person/model.js` I mean the `person` class. However the following [pre-defined template functions](https://www.jetbrains.com/help/idea/2016.2/live-template-variables.html) return nothing:
* `className`
* `jsClassName`
* `completeClassName`

`fileName()` of courses returns `model.js` which isn't what I need.

What do you think of adding the plumbing to make `jsClassName` work or create a new one like `emberCliPodName()`?

Also ideally it would be possible to get the CamelCased name in addition to the dasherized name. Example: `employee-schedule` and `EmployeeSchedule`.

For clarity, the template I want to create is a yuidoc header, where the $NAME$ variable is the camel cased pod name.

```
/**
 * $END$
 *
 * @namespace Model
 * @class $NAME$ 
 * @extends DS.Model
 * @public
 */
```

**Comment by Turbo87** [comment]
I would certainly like that, but I have no clue yet how to implement it. Feel free to open a PR though! 👍

**Comment by Turbo87** [comment]
since pods are essentially deprecated I'm not going to put any more work in on supporting them in this plugin, sorry
