### ISSUE TITLE
Can't import project after installing node modules

### ISSUE THREAD

**Issue by dwickern** [Turbo87/intellij-emberjs#110]
I found this while testing with [crates.io](https://github.com/rust-lang/crates.io). Not sure if it's a bug in the plugin or IntelliJ.

If I install node modules then try to import the project, IntelliJ detects the project root as some Java code in `node_modules`:

<img width="925" alt="screen shot 2016-11-23 at 11 47 11 am" src="https://cloud.githubusercontent.com/assets/752885/20576464/e8d070d8-b172-11e6-83fb-74e3eab2e5d7.png">

Workaround is to delete `node_modules`, then import the project, then `npm install`

**Comment by Turbo87** [comment]
@dwickern looks like the Java detector has a high priority 😕 

fortunately though you don't have to "import from existing sources" anymore, you can just open the project folder and the Ember CLI framework should be detected automatically.

**Comment by dwickern** [comment]
Huh, that does work. I thought I tried that.

The docs are a bit out of date then, but I'll close this.
