### ISSUE TITLE
Quick navigation to matching test file

### ISSUE THREAD

**Issue by adc-mhaugen** [Turbo87/intellij-emberjs#112]
Thanks for this plugin, it really helps.  I was wondering if it would be possible to get quick navigation to corresponding tests from components/routes/controllers, etc.  For example, if I'm in a component JS file, could we select a menu item, or hit a keystroke combo that would open the integration test for that component?

**Comment by Turbo87** [comment]
@adc-mhaugen that should already work. have a look at https://github.com/Turbo87/intellij-emberjs/blob/master/doc/features.md#navigate--related-symbol

**Comment by adc-mhaugen** [comment]
Thanks so much for the quick answer.  If I'm in a component file and I hit Navigate > Related Symbol I get a "Choose Target" popup where I can choose between the component file and the template.  If I'm in the component template it takes me straight to the JS file.  If I'm in the test it allows me to choose between modules I've imported into that test.  I don't see an option to toggle between the component and the test.  Perhaps there is a problem in my project configuration?

**Comment by Turbo87** [comment]
![bildschirmfoto 2016-12-09 um 15 49 48](https://cloud.githubusercontent.com/assets/141300/21052825/23c42e30-be27-11e6-86f8-575106fce464.png)

this is how it should look like if you use the default folder structure for your project. in this case I've used https://github.com/TryGhost/Ghost-Admin as an example.

**Comment by adc-mhaugen** [comment]
I see.  Perhaps it's because we are using the pod structure?  Regardless, the related symbol is still really useful.

**Comment by Turbo87** [comment]
Yeah, pods could be a reason for that. Since pods is essentially deprecated and will be replaced by the new module unification rfc thingy I've chosen to not put anymore work into supporting that though. I hope you understand...

**Comment by adc-mhaugen** [comment]
Sure, that make sense.  Thanks again!
