### ISSUE TITLE
Nested component dot path completion should be replaced with slash (/) path completion

### ISSUE THREAD

**Issue by Ramblurr** [Turbo87/intellij-emberjs#113]
For nested component templates, intellij-emberjs currently offers `.`  completion.

Example:

![core-group_template_hbs_-_rug_-____src_cropster-maude_](https://cloud.githubusercontent.com/assets/14830/21190901/bf547120-c223-11e6-85cb-e02da7b7a224.png)

However, with Ember 2.10 the `.` syntax is no longer supported and [everyone should switch to `/` syntax](https://github.com/emberjs/ember.js/issues/14224#issuecomment-265566966).

**Comment by Turbo87** [comment]
good point, thanks!

**Comment by nadnoslen** [comment]
Upvote.

(Thanks again for this plugin)

**Comment by Turbo87** [comment]
@Ramblurr @nadnoslen this should be a relatively easy bugfix, feel free to open a pull request for this :)

**Comment by Ramblurr** [comment]
I poked into the source seeing if I could add this relatively easily, but wasn't succesful. Here's what I tried. Keep in mind this is my first time around this part of the IntelliJ SDK.

The `com.emberjs.hbs.HbsReferenceContributor` registers two element patterns with the `HbsComponentReference`.

1. `HbsPatterns.BLOCK_MUSTACHE_NAME`
2. `HbsPatterns.SIMPLE_MUSTACHE_NAME`

I figured these patterns needed to be updated to support `/` as well as `.` triggers. There doesn't seem to be any explicit reference to `.` (DOT) as a separator, so I am assuming it is the default. The handlebars plugin itself uses slash and dot as separator types in its grammar  ([ref1](https://github.com/dmarcotte/idea-handlebars/blob/13ff3fdbb6972d9476ae99a7cb4e6373e782e264/src/com/dmarcotte/handlebars/parsing/HbTokenTypes.java#L58), [ref2](https://github.com/dmarcotte/idea-handlebars/blob/13ff3fdbb6972d9476ae99a7cb4e6373e782e264/src/com/dmarcotte/handlebars/parsing/handlebars.flex#L155)). So I figured these patterns needed to be updated to use `HbTokenTypes.SEP`, however I can't find any place to add this that works.

The obvious place was the two patterns registered with `HbsComponentReference`, but adding 
`            .afterLeaf(psiElement(HbTokenTypes.SEP))` to `SIMPLE_MUSTACHE_NAME` and `BLOCK_MUSTACHE_NAME` doesn't seem to work.

@Turbo87  any tips or pointers?

**Comment by Turbo87** [comment]
@Ramblurr actually we don't seem to be caring about the separator that much in the HBS AST at all. I guess the magic is in https://github.com/Turbo87/intellij-emberjs/blob/master/src/main/kotlin/com/emberjs/lookup/EmberLookupElementBuilder.kt#L11, but I'm not sure right now where else that class is used, so be careful about just removing that line.

**Comment by nadnoslen** [comment]
I have a couple of quite large Ember applications that have a hundred or more components, some nested in directories, some not.  I've leveraged the auto-complete of my IDE using this plugin and have dug a deep hole where it concerns making my app Glimmer2-ready.

I took a little time yesterday to write a Ruby script that combs through my EmberJS application and replaces MOST (not all) dot-notation paths with slash-notation.  It may be helpful to others: [https://github.com/cybertoothca/emberjs-component-dot-to-slash-paths](https://github.com/cybertoothca/emberjs-component-dot-to-slash-paths)

Cheers.

**Comment by Turbo87** [comment]
@dwickern in addition to #119, do you think it would make sense to write a quickfix that converts from dots to slashes automatically?

**Comment by dwickern** [comment]
@Turbo87 [ember-watson](https://github.com/abuiles/ember-watson) might be a better fit for that sort of thing

**Comment by nadnoslen** [comment]
Hey Gang,
Thanks for the fix!  However, I'm now noticing that **route** auto-completion is not following dot-notation.  In the Ember Guide (https://guides.emberjs.com/v2.10.0/routing/defining-your-routes/#toc_nested-routes):

> A nested route's names includes the names of its ancestors. If you want to transition to a route (either via transitionTo or {{#link-to}}), make sure to use the full route name (posts.new, not new).

I'm pretty sure these should stay with the dot-notation.  Any thoughts?

(PS. thanks for the note about ember-watson)

**Comment by Turbo87** [comment]
@nadnoslen looks like we missed that part 😞 

could you open a separate issue for that and crosslink this issue here?
