### ISSUE TITLE
Project detection not working in PHPStorm

### ISSUE THREAD

**Issue by Ramblurr** [Turbo87/intellij-emberjs#121]
The plugin is working great in IntelliJ, however one of our devs uses PHPStorm, which AFAIK is Webstorm + PHP support.

When he attempts to create a new PHPStorm project from existing files, the ember project detection doesn't work.

1. File -> "New Project from existing files" leads to this dialog:
    ![upload](https://cloud.githubusercontent.com/assets/14830/21925841/82b9e61e-d97f-11e6-8a6c-0c728475d6c8.png)
2. Select an existing ember project in the file dialog
3. It is detected as a Web project, but the ember.js framework is not detected.

result: no ember plugin features are enabled

Also using `File -> Open` and selecting the folder does not work.

Apparently this *used to work* at some point in the past, but it no longer does. I suspect it used to work when the plugin was using a Ember project type, before the switch to the framework.

**Comment by Turbo87** [comment]
@Ramblurr tl;dr is that we've replaced our previous framework detection with an `FrameworkDetector` implementation. this means that you can just open the folder of an Ember app in the IDE and it will detect Ember projects and offer to reconfigure the IDE for you.

What PHPStorm version is your dev using?

**Comment by mydea** [comment]
Hey,

I'm using the latest version, PhpStrom 2016.3.2, and the latest version of the Ember.js plugin.
I just tried again, just opening an ember app/addon in the IDE does not trigger the Ember.js plugin.

**Comment by Turbo87** [comment]
@mydea thanks for the feedback. I'll see if I can find out what's going on.

**Comment by mydea** [comment]
Oh, and as a note, I'm running Windows 10, not sure if that can have anything to do with it.

**Comment by dwickern** [comment]
I was able to reproduce this in PHPStorm 2016.3.2

**Comment by dwickern** [comment]
I can't seem to get the FrameworkDetector working. Maybe it's not supported in PHPStorm? I would test how the angular plugin works in PHPStorm if I had more time.

What I can do for you right now is fix our ProjectConfigurator. This would let you open an ember app in the root project folder but not detect ember projects in subdirectories.

**Comment by mydea** [comment]
That would be awesome and absolutely good enough.
As a side note, I've seen that e.g. Laravel has a setting that you can toggle the plugin manually, `Enable this plugin for this project`. Not sure if that would be an option, but it seems nice (and also makes it quite easy to check if the project detection has actually worked).

**Comment by cbornhoft** [comment]
Can confirm this is is not working in PhpStorm 2016.3.2 for our devs as well. I'll try out the fork and see if that fixes it!

**Comment by Turbo87** [comment]
this should be fixed as best as we can by #127 and will be released as v2016.3.5 soon
