### ISSUE TITLE
Code colors are being changed

### ISSUE THREAD

**Issue by lvegerano** [Turbo87/intellij-emberjs#126]
I use color to visually locate certain things in the code. In this case the styles of parameters inside a `js` function is carried into the function itself but it breaks once the plugin is installed 😢 .

http://quick.as/zvDetmmLa

**Comment by Turbo87** [comment]
@lvegerano sorry, I have no idea how we could possibly break that behavior with our implementation. feel free to debug this though if you have a bit of time.
