### ISSUE TITLE
Nested Route Paths Should Use dot-notation

### ISSUE THREAD

**Issue by nadnoslen** [Turbo87/intellij-emberjs#128]
A recent change made in issue #113 has broken the proper dot-notation auto-completion for Route (and Controller) paths.  For example, in template references using `{{link-to}}`:

    {{#link-to "some/nested/directory/route"}}Link Label{{/link-to}}
    {{!-- should instead be written: --}}
    {{#link-to "some.nested.directory.route"}}Link Label{{/link-to}}

and in JS references:

    // app/routes/some/nested/directory/route.js
    model() {
      // return this.modelFor('some/nested/directory');
      // should instead be written:
      return this.modelFor('some.nested.directory');
    }

As best I can tell from the Ember guides, API documentation and my personal use of the EmberCLI generators; nested directory paths for _models_, _components_, & _helpers_ should be referenced using typical slash-notation **while _route_ (and even _controller_) paths should instead use dot-notation**.

@rwjblue explains some of this over here: https://github.com/emberjs/ember.js/issues/14224#issuecomment-245274336

## Additional Information

The [Ember Guide's](https://guides.emberjs.com/v2.11.0/routing/defining-your-routes/#toc_nested-routes) examples and Ember API documentation indicate that nested route paths should be defined using dot-notation.

* [`{{link-to}}`](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_link-to)
* [`Route#controllerFor(...)`](http://emberjs.com/api/classes/Ember.Route.html#method_controllerFor)
* [`Route#intermediateTransitionTo(...)`](http://emberjs.com/api/classes/Ember.Route.html#method_intermediateTransitionTo)
* [`Route#modelFor(...)`](http://emberjs.com/api/classes/Ember.Route.html#method_modelFor)
* [`Route#render(...)`](http://emberjs.com/api/classes/Ember.Route.html#method_render)
* [`Route#replaceWith(...)`](http://emberjs.com/api/classes/Ember.Route.html#method_replaceWith)
* [`Route#transitionTo(...)`](http://emberjs.com/api/classes/Ember.Route.html#method_transitionTo)

**Comment by dwickern** [comment]
@rwjblue to clarify, we should use slashes for component invocations inside templates (`{{foo/bar/baz}}` or `{{yield (component "foo/bar/baz")}}`) and dots everywhere else (link-to, javascript code)?

**Comment by Turbo87** [comment]
@dwickern yes, I think thats correct
