### ISSUE TITLE
Feature Request: Run configuration with debug mode

### ISSUE THREAD

**Issue by mohamnag** [Turbo87/intellij-emberjs#132]
That would be very nice for fast inspection of states and variables if there was a way to debug an ember app using intellij. I found [this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/207632025-Debugging-an-Ember-application) which I'm not sure if has been further considered or not, but maybe there could be some configuration done in ember-cli config so that it generates proper map files.

the [run configuration](http://stackoverflow.com/questions/37271604/run-configuration-with-command-line-program-in-intellij-idea) itself is rather easy to do but the real value is in debugging.

**Comment by Turbo87** [comment]
see https://github.com/Turbo87/intellij-emberjs/pull/109

**Comment by mohamnag** [comment]
oops sorry, just searched between issues. thx
