### ISSUE TITLE
Support for pods style in autocomplete

### ISSUE THREAD

**Issue by joegaudet** [Turbo87/intellij-emberjs#134]
Use case:

Our project has components organized in the following way

features
+-- components
       +-- foo

The autocomplete in handlebars is always prefixing features/components on my templates, similarly when autocompleting routes it prefixes the string with features.

Would be good to have something like 'component root' and 'route root' ?

**Comment by Turbo87** [comment]
@joegaudet I'm not sure I understand. Can you add a screenshot of the autocompletion not working as expected?

**Comment by joegaudet** [comment]
So heres trying to auto complete a component, but components helpers are loaded from /feature/components and not /

![screen shot 2017-02-28 at 9 09 26 am](https://cloud.githubusercontent.com/assets/123911/23415979/e2c6639a-fd95-11e6-80cc-1e41926f7d72.png)
![screen shot 2017-02-28 at 9 09 51 am](https://cloud.githubusercontent.com/assets/123911/23415978/e2adc8c6-fd95-11e6-844a-90a77e6a8b08.png)

Similarly here, I would have expected the linkto autocomplete to produce a dot delimited route from features.

![screen shot 2017-02-28 at 9 10 38 am](https://cloud.githubusercontent.com/assets/123911/23415980/e2cb60b6-fd95-11e6-8d12-d2d0bb7f727a.png)
![screen shot 2017-02-28 at 9 11 13 am](https://cloud.githubusercontent.com/assets/123911/23415981/e2ccf7aa-fd95-11e6-90bb-0989dccb2156.png)

**Comment by joegaudet** [comment]
@Turbo87 Is this something that might be possible?

**Comment by Turbo87** [comment]
it might be possible, but since pods are essentially deprecated I will not work on this myself. feel free to work on an implementation of this though.

**Comment by Turbo87** [comment]
closing this for now

**Comment by joegaudet** [comment]
@Turbo87 wondering how hard this might be? Seems like module unification is still a ways away this would be pretty handy.

Not sure where you'd even start mind you, but happy to look into it if you have some guidance
