### ISSUE TITLE
Support jumping to components in subdirectories based on . notation

### ISSUE THREAD

**Issue by tylergets** [Turbo87/intellij-emberjs#135]
The editor autocompletes components that are in subdirectories of the component folder using dot notation, however jumping with CMD+B does not work.

**Comment by Turbo87** [comment]
@tylergets what version of the plugin are you using? it should autocomplete with slash separators in the most recent version and reference lookup works for me too for nested components.

**Comment by tylergets** [comment]
Is slash preferred over dot? Its likely my plugin needs updating.

**Comment by Turbo87** [comment]
yes, dots was never supposed to be supported and support for that was removed in a recent Ember release iirc

**Comment by Turbo87** [comment]
see https://github.com/Turbo87/intellij-emberjs/issues/113
