### ISSUE TITLE
Add support for "ember-template-lint"

### ISSUE THREAD

**Issue by Turbo87** [Turbo87/intellij-emberjs#136]
see https://github.com/rwjblue/ember-template-lint

/cc @rwjblue

**Comment by makepanic** [comment]
Some possible ideas on how to solve this issue:
- run template-lint as [cli executable](https://github.com/rwjblue/ember-template-lint#cli-executable) for each file that's expected to be linted
- get "inspiration" from the open source [eslint plugin](https://github.com/idok/eslint-plugin)

**Comment by Turbo87** [comment]
@makepanic I think if we want to take inspiration from the ESLint integration we should look at the built-in functionality of IntelliJ (or their JS plugin), instead of an external plugin.

**Comment by makepanic** [comment]
👍 it's located in

`
/ideaIU-173.3622.25/plugins/JavaScriptLanguage/lib/JavaScriptLanguage.jar!/com/intellij/lang/javascript/linter/eslint
`

**Comment by makepanic** [comment]
started working on this in https://github.com/makepanic/intellij-emberjs/tree/hbs-lint

![20191229-201232](https://user-images.githubusercontent.com/1205444/71561939-9ce8c300-2a7d-11ea-9a78-3a42c9ee4286.png)
![20191229-201246](https://user-images.githubusercontent.com/1205444/71561940-a07c4a00-2a7d-11ea-9e69-5418eee086ca.png)

It's currently heavily inspired by `stylelint` intellij linting implementation.
There are some open questions that I'm not sure of:

1. is template-lint using any fallback configuration files or is it only `.template-lintrc.js`?
2. where should we allow the user to specify a custom configuration file? (probably the lint settings widget)
3. what Icon should we use? The stylelint integration uses one
4. how should the setting be called? The branch uses `TemplateLint`
