### ISSUE TITLE
better addons support

### ISSUE THREAD

**Issue by IgorKvasn** [Turbo87/intellij-emberjs#144]
Hi,
addon support was introduced in the latest release, however it supports file navigation only within `app/` directory. It is still not possible to navigate to files in `addon/` directory.
(note: I am testing it on in-repo addon - I am not sure if it works on a regular addons).
Could you pls support `addon/` directory as well?

**Comment by IgorKvasn** [comment]
this is my addon's file structure (addon is called _form-config_) - notice that component `field-modul` is in `addon/` as well as `app/` directory

![image](https://user-images.githubusercontent.com/2052652/27039386-1739906c-4f8e-11e7-904d-ebbfc753ef96.png)

however when I search for a class `field-modul` I get only one result in  `app/` directory:
![image](https://user-images.githubusercontent.com/2052652/27039525-7880cb92-4f8e-11e7-9238-2601d23fef21.png)

I would expect to see both components/files listed in the search results

AFAIK only thing different from running a simple `ember g component x-foo -ir search` command is the `pods/` sub-directory in `app/`...

let me know if you need some more info

**Comment by dwickern** [comment]
Unfortunately some of this plugin's features are not implemented for pods. Since pods are no longer supported by ember-cli, we feel that our limited time is better spent elsewhere. Sorry about that :(
