### ISSUE TITLE
Import ember modules

### ISSUE THREAD

**Issue by vendethiel** [Turbo87/intellij-emberjs#152]
Hi,

I'm trying to figure out if there's a way to get IntelliJ to recognize correctly the imports from ember.

i.e. 
![image](https://user-images.githubusercontent.com/199499/28519263-2dde2b40-706b-11e7-8d29-1b99f1a9316b.png)

In the first case, it's simply that "ember" doesn't exist.
In the second case, it's because emberjs addons use a specific layout, so the file actually isn't in that path.

Is there a way around it?

**Comment by Turbo87** [comment]
the second one should actually work. what version of the plugin are you on?

**Comment by vendethiel** [comment]
2017.2.1-0

**Comment by vendethiel** [comment]
Just to be clear, for the second one:

![image](https://user-images.githubusercontent.com/199499/28522070-dbfc1876-7076-11e7-878f-3b9ce9126230.png)

The "addon" folder is what bugs it out.

If I write

```
import AuthenticatedRouteMixin from 'ember-simple-auth/addon/mixins/authenticated-route-mixin';
```

then intellij can find it (but it's incorrect obviously).

**Comment by Turbo87** [comment]
@dwickern any idea why this might not be working?

**Comment by dwickern** [comment]
I have the same problem on plugin version 2017.2.1-0 but it works fine on master branch 🤔

**Comment by vendethiel** [comment]
When I compare between 2017.2.1 and master: https://github.com/Turbo87/intellij-emberjs/compare/v2017.2.1...master

I see this commit: d760843614c1e766eab64a0c21cd5d80c586ce95

Seems to be it?

**Comment by vendethiel** [comment]
Can I close this?
