### ISSUE TITLE
Exclude /blueprints folder

### ISSUE THREAD

**Issue by patric-eberle** [Turbo87/intellij-emberjs#161]
For our projects we use some customized blueprints. Those are indexed as well by default, but not needed in general production. Would be nice if this folder (/blueprints/*) could be excluded automatically as well like node_modules/bower_components.

**Comment by Turbo87** [comment]
I don't think that would be a good idea in general for people that develop blueprints. Since you can easily add the exclusion manually I won't implement this here. Sorry!
