### ISSUE TITLE
Inspection: Unused default module for 'export default' 

### ISSUE THREAD

**Issue by mk-conn** [Turbo87/intellij-emberjs#163]
In every ember component, route, etc... this inspection error comes up. I already wrote Jetbrain Support about it, but they pointed on the emberjs plugin. I can not really verify that the plugin is the cause for this... 
![screen shot 2017-10-16 at 00 52 09](https://user-images.githubusercontent.com/5840922/31590186-59de3784-b20c-11e7-8dc9-f416cba2d9bc.png)

**Comment by Turbo87** [comment]
@mk-conn that is a built-in inspection of IntelliJ and not really related to this plugin. I'd recommend to just turn of the inspection completely for Ember.js projects.
