### ISSUE TITLE
Support  for Ember addons?

### ISSUE THREAD

**Issue by panthony** [Turbo87/intellij-emberjs#17]
It would be nice to have a minimal support of ember addons.

See https://gist.github.com/kristianmandrup/ae3174217f68a6a51ed5

**Comment by Turbo87** [comment]
I haven't yet developed any addons myself so I'm not quite aware of what exactly might be useful there, but this is definitely something that is planned for a future release.

**Comment by Turbo87** [comment]
@panthony I added basic addon support in #19. No name resolution yet like for real apps, but at least the project detection is working now in IntelliJ.

**Comment by panthony** [comment]
nice :+1:
