### ISSUE TITLE
Add support for monorepos

### ISSUE THREAD

**Issue by teejayhh** [Turbo87/intellij-emberjs#179]
We as a company have adopted the monorepo (https://developer.atlassian.com/blog/2015/10/monorepos-in-git/) structure to have access to multiple addons and apps all at once.  This kind of structure makes it easier to work with addons accross multiple apps. Unfortunately this addon doesn't really work with monorepos as the cli file is not located in the root but in each applications / addon. Therefore it's not possible to resolve the paths properly, which is a shame and kinda frustrating. I am wondering if its possible to implement mono repo support for the plugin.

Cheers Thomas

**Comment by dwickern** [comment]
We depend on framework detectors to import from subdirectories, which only works in IDEA according to the WebStorm lead: https://github.com/Turbo87/intellij-emberjs/pull/127#issuecomment-274816296. I'm not sure if multiple apps/addons at the same time will work. Maybe you could try with an evaluation license of IDEA and report back?

**Comment by teejayhh** [comment]
Sorry I didn't try this yet.
