### ISSUE TITLE
Run Configuration per module

### ISSUE THREAD

**Issue by huberts** [Turbo87/intellij-emberjs#181]
Hi!
It would be great to add selecting module/working directory in Ember Serve Configuration. 
Right now, my project contains multiple modules (one of them is EmberJS) and I cannot use the ES Configuration.

**Comment by makepanic** [comment]
Hi @huberts,
would something like the nodeunit `Working directory` picker be enough to solve your issue?

![20180102-130105](https://user-images.githubusercontent.com/1205444/34483504-2ea89c8a-efbf-11e7-9fa7-6f84df3de389.png)

**Comment by huberts** [comment]
I think so. It would be great :-)

**Comment by makepanic** [comment]
@Turbo87 should `Working directory` be under `Advanced settings` or an always visible option?

**Comment by Turbo87** [comment]
Can't we detect the right one automatically?

**Comment by makepanic** [comment]
You mean to only allow configuring known `EmberModuleType` modules?
That also works. 

I've tinkered around and `myModulesComboBox?.fillModules(serveConfiguration.project, EmberModuleType.instance)` in combination with a `com.intellij.application.options.ModulesComboBox` creates a usable result:

![20180102-190136](https://user-images.githubusercontent.com/1205444/34495699-a8f37ec4-eff6-11e7-94f1-e1f26631bfb9.png)

**Comment by Turbo87** [comment]
yeah, something like that. make sure to automatically select one of the options by default instead of using `[none]`

**Comment by makepanic** [comment]
We could also disallow empty selection. The screenshot above explicitly allowed it via `allowEmptySelection`
