### ISSUE TITLE
how about some goto convience

### ISSUE THREAD

**Issue by DuckoDeath** [Turbo87/intellij-emberjs#189]
How about the ability to:
- from a component .js, goto the .hbs (and vice versa).
- from anything, goto the test

just a right click goto->test/template would be awesome
Is this possible?

**Comment by dwickern** [comment]
We have this actually 😄 
`Navigate -> Related symbol`

**Comment by DuckoDeath** [comment]
ah yes, nice!!
But, missing test navigation me thinks.
