### ISSUE TITLE
autocomplete for components with pods structure doesn't work

### ISSUE THREAD

**Issue by bedrosenator** [Turbo87/intellij-emberjs#190]
After last update I noticed that autocomplete for components in templates with pods structure doesn't work

**Comment by Turbo87** [comment]
what specifically do you mean by "last update"?

**Comment by bedrosenator** [comment]
There was update from jetbrains for webstorm. And I updated emberjs plugin for webstorm IDE. So current version is 2017.3.2-0
With previous version of this plugin autocomplete works well

**Comment by Turbo87** [comment]
which version did you use before?

**Comment by bedrosenator** [comment]
I'm not sure what version was that, but there were different icons for routes, models , services. Hmm.., Maybe it is jetbrains downgraded that plugin version in their last update

**Comment by bedrosenator** [comment]
Sorry, this not an issue of your plugin. I've installed it manually in webstorm and it works well. So it is an issue of webstorm update
Thanks for fast answer

**Comment by Turbo87** [comment]
okay, thanks for the feedback
