### ISSUE TITLE
Ember Serve Run configuration broken after update to 2018.1.1

### ISSUE THREAD

**Issue by iqdoq-dfischer** [Turbo87/intellij-emberjs#191]
Updated WebStorm from 2017.3.5 to WebStorm 2018.1.
The same Ember Serve Run Configuration worked in 2017.3.5.
After the update to WebStorm 2018.1 and updating the Ember Plugin to 2018.1.1-0 the following error is printed to the run console after hitting the Run button:

"C:\Program Files\nodejs\node.exe" C:/Users/dfischer/sources/iqdoq/product/HyperDoc-HEAD/web-ui/node_modules/.bin/ember.cmd serve
C:\Users\dfischer\sources\iqdoq\product\HyperDoc-HEAD\web-ui\node_modules\.bin\ember.cmd:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Process finished with exit code 1

**Comment by Turbo87** [comment]
@makepanic any ideas?

**Comment by makepanic** [comment]
I'm not sure if this is related to the ember addon.
I'm on Intellij 2018.1 (linux) and the serve run configuration works without issues.

@iqdoq-dfischer does ember-cli work for you without using Webstorm? Try to nuke the node_modules in web-ui and reinstall.

From the error, it looks like somehow cmd code got mixed with JavaScript.
Maybe it's a upstream ember-cli issue :thinking: 
Can you also dump the content of `web-ui\node_modules.bin\ember.cmd` if possible?

**Comment by iqdoq-dfischer** [comment]
I have nuked my node_modules folder and reinstalled all modules with npm install. Same problem.
After that I upgraded my Ember version from 2.17.2 to the latest LTS version (currently 2.18.2). Problem persists.

@makepanic ember-cli works inside my web-ui folder from the windows command line: ```C:\..somelongpath..\web-ui>node_modules\.bin\ember.cmd serve``` starts the ember web server successfully so I guess it is not an upstream ember-cli issue.

If I run the command on the command line like the webstorm ember serve run configuration does, I have the same issue:
```
C:\..somelongpath..\web-ui>"C:\Program Files\nodejs\node.exe" C:/Users/dfischer/sources/iqdoq/product/HyperDoc-HEAD/web-ui/node_modules/.bin/ember.cmd serve
C:\Users\dfischer\sources\iqdoq\product\HyperDoc-HEAD\web-ui\node_modules\.bin\ember.cmd:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
The contents of node_modules\.bin\ember.cmd from Ember-cli 2.18.2:
```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\ember-cli\bin\ember" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\ember-cli\bin\ember" %*
)
```

If I directly call the ember javascript code like that it works too:
```"C:\Program Files\nodejs\node.exe" C:/Users/dfischer/sources/iqdoq/product/HyperDoc-HEAD/web-ui/node_modules/ember-cli/bin/ember serve```

I suggest changing the ember serve run task call in the webstorm ember plugin to that in the line above.

**Comment by makepanic** [comment]
Can you maybe check if any of the generate functions work?
i.e. generate a route or service using the plugin.

**Comment by iqdoq-dfischer** [comment]
Tried to create a new route via "Generate Ember.js Files". That doesn't work either:

Webstorm event log:
```
13:30	Problem running ember-cli:
			Process did not exit properly (code = 1). Please try again on the command line.
```

**Comment by makepanic** [comment]
I guess it's a general problem on windows in how we generate `commandLine` in EmberCli.

**Comment by makepanic** [comment]
I think I may know what the issue is.
On windows the current impl tries to execute the generated `ember.cmd` with node. Sadly the cmd isn't written/generated in JavaScript so it throws a SyntaxError.
If we either execute the ember script (without cmd) with node, or not run node but execute the ember.cmd directly, it should work.

@Turbo87 do you think this causes the issue? If so, what way do you prefer.
@iqdoq-dfischer can you confirm that `\web-ui\node_modules\.bin\ember` exists and is a JavaScript file?

**Comment by makepanic** [comment]
I'd think that executing `.bin/ember(.cmd)` is the better way as it automatically detects nodejs.
Also it allows cli to move its cli script without us having to update any paths, as it's configured in the package.json.

**Comment by makepanic** [comment]
@iqdoq-dfischer with https://github.com/Turbo87/intellij-emberjs/pull/210 merged, this should work in the latest ember intellij version. (If it's really the same issue)

Can you confirm and maybe close this issue?

**Comment by iqdoq-dfischer** [comment]
Sorry my answer is a little bit late but better late than never:
Works with WebStorm 2018.3.3 and Ember plugin 2018.3.2.

Thank you very much!
Closing this issue.
