### ISSUE TITLE
Add support for angle bracket components

### ISSUE THREAD

**Issue by Turbo87** [Turbo87/intellij-emberjs#204]
to support e.g. https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill

**Comment by km-smith** [comment]
Came here to say this but you are on top of things.

**Comment by donaldwasserman** [comment]
@Turbo87 is this something that you still need or is it a WIP?

**Comment by Turbo87** [comment]
it's still needed

**Comment by jpveilleux** [comment]
Any news on the progress of this? This is an integral part of Ember now and should be supported ASAP ;)

Thanks for the great plugin btw!

**Comment by makepanic** [comment]
I've started investigating this in the last couple weeks and it seems we can't just reuse the `HbsReferenceContributor` as it's only handling the parsed handlebars tree.

Next I'll try to build a `TagDescriptorsProvider` which implements `XmlElementDescriptorProvider, XmlTagNameProvider` , similar to the [ng2 implementation](https://github.com/JetBrains/intellij-plugins/blob/master/AngularJS/src/org/angular2/codeInsight/tags/Angular2TagDescriptorsProvider.java).

The intellij plugin docs are pretty lacking :(

**Comment by Turbo87** [comment]
> The intellij plugin docs are pretty lacking :(

oh yes... 🙈

**Comment by vsergiu93** [comment]
Any news on this? 

It's an awesome plugin, thank you for your work.

**Comment by makepanic** [comment]
Sadly I didn't have any more time.
I think the most sane solution would be to fork the handelbars plugin and extend [their flex grammar](https://github.com/JetBrains/intellij-plugins/blob/master/handlebars/src/com/dmarcotte/handlebars/parsing/handlebars.flex) to support what we need.

Alternatively we could write our own gramma, similar to the ng2 plugin. That would be tons of work though :(

**Comment by Turbo87** [comment]
@makepanic I'm not sure why we need a custom grammer for this. I've tried to implement it using a regular ReferenceContributor, but for some reason the references were not clickable at all.

As much as I like developing in IntelliJ, writing plugins for it is a real pain in the ...

**Comment by makepanic** [comment]
Interesting. I've tried to extend the HbsPatterns to get proper results but it seemed like i can only use the tokens that the handlebars library finds. 
Somehow i only got handlebars syntax and everything else was transparent. Don't we need access to the "html" tokens too (aka angle bracket tokens)?

**Comment by Turbo87** [comment]
yeah, the `HbsReferenceContributor` is limited to the Handlebars PSI. Angle Bracket Components are part of the HTML PSI though, so they would need their own dedicated reference contributor AFAICT.

**Comment by rohitpaulk** [comment]
Looks like this was added in https://github.com/Turbo87/intellij-emberjs/pull/293?
