### ISSUE TITLE
Incorrect commands

### ISSUE THREAD

**Issue by Hucster** [Turbo87/intellij-emberjs#207]
1. creating new route:
![image](https://user-images.githubusercontent.com/40205811/41293214-60d45218-6e5d-11e8-941e-379d59a2c864.png)

2. runing ember serve:
![image](https://user-images.githubusercontent.com/40205811/41293393-ce7b6446-6e5d-11e8-90a3-45395873537a.png)

It seems like the node.exe is redundant. Tried with Ember.js-2018.2.1-0 and Ember.js-2018.1.2-0.

**Comment by Turbo87** [comment]
@makepanic any ideas?

**Comment by makepanic** [comment]
Sounds like https://github.com/Turbo87/intellij-emberjs/issues/191#issuecomment-379168826

Basically it seems like the cmd generation on windows is broken.

**Comment by Hucster** [comment]
I can check on Windows. Send me or give the link to patched Ember.js-2018.1.2-0
