### ISSUE TITLE
Switch to related style file

### ISSUE THREAD

**Issue by Turbo87** [Turbo87/intellij-emberjs#211]
When using SASS it seems to be a common pattern to have a `styles/components/` folder with one SASS file per component with matching names. We could detect this pattern and suggest it as another related file for components.

**Comment by azhiv** [comment]
Absolutely agree. I often feel lack for this navigation option.

**Comment by Turbo87** [comment]
this has been implemented for https://github.com/salsify/ember-css-modules :)
