### ISSUE TITLE
Plugin is Freezing WebStorm 11

### ISSUE THREAD

**Issue by jackmatt2** [Turbo87/intellij-emberjs#22]
In my workspace I have about 11 ember projects.  As soon as I installed this plugin "WebStorm 11" now freezes. Previously, I had to add both `bower_components` and `node_modules` to the excluded list (right click > mark directory as > exclude) to prevent webstorm from indexing them in searches which was causing the same behaviour.  I noticed that the plugin instead adds them as libraries, maybe this is causing the issue.

**Comment by Turbo87** [comment]
maybe this should be a bug report on the webstorm issue tracker instead? what's the point of indexing if the ide doesn't even know about the installed libs?

**Comment by panthony** [comment]
I kind of agree with @Turbo87, the issue would be more on WebStorm "while indexing huge project, the IDE is irresponsive".

Although I understand as I use to exclude both folders for the same reason (I'm using IntelliJ).

But it should come back to normal once the project is indexed no?

**Comment by Turbo87** [comment]
what we could do is offer a plugin-wide option to add those folders to the exclude list instead, but I won't have time to work on this in the next few weeks while on vacation. I'd be happy to review and merge when I get back though.

**Comment by panthony** [comment]
It may be the occasion to add a configuration panel of the plugin with this configuration and the ember binary path :)

I hope I'll have some time to take a look before you get back but I never played with kotlin nor intellij plugin before.

**Comment by Turbo87** [comment]
closing this in favor of #24 which explicitly states the necessary steps to resolve these issues
