### ISSUE TITLE
Not available for RubyMine 8

### ISSUE THREAD

**Issue by captmorgan** [Turbo87/intellij-emberjs#23]
I wasn't able to find the plugin listed under "Browse Repositories".

**Comment by captmorgan** [comment]
I tried building the plugin locally but when I tried to install I received an error that it was not compatible.

**Comment by Turbo87** [comment]
hmm, it should work fine on the latest RubyMine version, but I admit that I only tested IntelliJ, PyCharm and WebStorm so far...

**Comment by Turbo87** [comment]
@captmorgan could you test if #20 works for you?

**Comment by sauy7** [comment]
Works for me on 8.0.3

**Comment by Turbo87** [comment]
@sauy7 awesome, thanks for the feedback!

**Comment by captmorgan** [comment]
sorry about the delay.  works for me as well.
