### ISSUE TITLE
Allow developer to configure Node interpreter

### ISSUE THREAD

**Issue by makepanic** [Turbo87/intellij-emberjs#241]
### Description

Various intellij node plugins allow a developer to specify Node interpreter and options:

- Mocha: 

![20181022-161028](https://user-images.githubusercontent.com/1205444/47298907-43833980-d619-11e8-8989-566a43252043.png)

- Node.js:

![20181022-161015](https://user-images.githubusercontent.com/1205444/47298939-56960980-d619-11e8-8eb2-54a012e87df9.png)

This would provide a way to fix https://github.com/Turbo87/intellij-emberjs/issues/238

@Turbo87 do you have any preferences on this? I think it's not that hard to implement.
I'm unsure if we need `Node options` but it's used by almost all node related plugins so I'd guess ember should behave similar

**Comment by Turbo87** [comment]
nope, no preferences here

**Comment by rinoldsimon** [comment]
npm lint:js  run configuration:
![screenshot 2018-10-23 at 08 01 22](https://user-images.githubusercontent.com/6988364/47331556-04e19380-d69a-11e8-8216-34edc6c33031.png)

Configuring node interpreter may solve #238

**Comment by makepanic** [comment]
@rinoldsimon if you have some time, can you check https://github.com/makepanic/intellij-emberjs/tree/issues/241 and see if it works for you? I started working on it back in october and had some time today to mostly finish it up for the serve config.

![20190404-210448](https://user-images.githubusercontent.com/1205444/55583453-3323ce80-5722-11e9-87d6-87164b161d24.png)

I still have to add it to the test config too. Then I'll open a valid PR.
