### ISSUE TITLE
Recognize that an action function is not an unused method and uses the higher level `this`

### ISSUE THREAD

**Issue by mihai-scurtu** [Turbo87/intellij-emberjs#25]
<img width="377" alt="screen shot 2016-01-14 at 2 50 41 pm" src="https://cloud.githubusercontent.com/assets/5492517/12324828/445b0f04-bace-11e5-99ec-0e466ee18b14.png">

The screenshot is from inside a component.

**Comment by Turbo87** [comment]
that would be cool, but I think it is (at least for now) out of scope for the plugin. feel free to work on it though, I'd be happy to review and merge any pull requests.
