### ISSUE TITLE
Make plugin compatible to IDEA 2019.1

### ISSUE THREAD

**Issue by ofry** [Turbo87/intellij-emberjs#250]
### Steps to Reproduce

**Expected behavior:** Plugin should be compatible with IntelliJ IDEA 2019.1

**Actual behavior:** Compatible versions is 2018.3.2 — 2018.3.6

**Reproduces how often:** 100%

### Versions

- The first two lines of the `Help` -> `About` output:

```
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
```

- The version of `intellij-emberjs` (`Settings` -> `Plugins` -> `Ember.js`):

**Comment by makepanic** [comment]
Can confirm that it's not working with the new version
![20190328-080339](https://user-images.githubusercontent.com/1205444/55138127-f9a3ff80-5132-11e9-93bc-d114107deda3.png)

I'll see if i can investigate/fix this in the evening

**Comment by km-smith** [comment]
@Turbo87 2019.1 was released on March 26, 2019. Looking forward to having your plugin work in the new version. It's the only blocker keeping me from migrating since it's quite essential to my dev workflow at this point.

**Comment by CezaryH** [comment]
+1

**Comment by Turbo87** [comment]
v2019.1.1 of the plugin was released about an hour ago
