### ISSUE TITLE
Generate ember file not available

### ISSUE THREAD

**Issue by mk-conn** [Turbo87/intellij-emberjs#252]
### Description

In the docs it says: 

> The Ember.js plugin can be used to quickly generate files using the generate command of ember-cli. This functionality is available as File → New → Ember.js Code.

<img width="330" alt="Screenshot 2019-04-02 at 13 45 41" src="https://user-images.githubusercontent.com/5840922/55401795-189afb00-5552-11e9-823f-fdd0a2467e76.png">

But I'm not seeing this functionality. Could it be, that the problem is related to the fact, that I have my ember folder not in the root of the project? 

My structure is as follows:
`app > resources > frontend` - frontend is the ember folder

### Versions

PhpStorm 2019.1
Build #PS-191.6183.95, built on March 27, 2019

2019.1.1-0

**Comment by makepanic** [comment]
Did you see intellij prompting you when it found an ember project?

If not, try to import the ember app as module in your project settings (`Project Settings -> Modules -> + -> Import module`). It should try to import it as ember project.

**Comment by mk-conn** [comment]
I don't have `Project Settings` ... in PhpStorm, IDEA has?

**Comment by mk-conn** [comment]
Okay... I was generating a new module by myself since PhpStorm does not offer this in the settings

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/5840922/55409168-c95cc680-5561-11e9-9a9a-56ca0808106e.png">

Now its working :) Thx for the hint!
