### ISSUE TITLE
Inheritance navigation and marking

### ISSUE THREAD

**Issue by JulienFr** [Turbo87/intellij-emberjs#255]
### Description

Components and services inherit variables and functions from parent components and services and also attached mixins. I as a developer, need to know what variables and functions are inherited in my components and services, and know about their origins, as otherwise the code is not navigable.

### Steps to Reproduce

parent-component.js

```
import Ember from 'ember';

export default Ember.Component.extend({
    myVariable: true, // inherited marker

    myFunction(): { // inherited marker
        // do something
    }
});
```

child-component.js
```
import ParentComponent from '../components/parent-component';

export default ParentComponent.extend({
    myVariable: false, // inheriting marker

    myFunction(): { // inheriting/overwritting
        this._super();

        // do something more after the parent
    }
});
```

**Expected behavior:**
I would expect a marker to indicate if a variable/function is inherited upward, and from whom it inherits. If I click on the marker, I get to the inherited variable/function of the parent.
![image](https://user-images.githubusercontent.com/4102307/55690558-691bb980-5993-11e9-8da4-39fe62b2f5c3.png)

I would expect a marker to indicate if a variable or function is inherited downward, bonus to know whom inherits. If I click on the marker, I get to the inherited variable/function of the parent.
![image](https://user-images.githubusercontent.com/4102307/55690573-9d8f7580-5993-11e9-8df3-1a15dbab28db.png)

**Comment by Turbo87** [comment]
this is quite hard to implement and since Ember will soon move to use ES6 classes by default this behavior will then be built-in anyway

you are welcome to work on this for the old Ember.Object system if you want to, but I'm personally not going to invest time in this if it will soon be unnecessary 😉

**Comment by JulienFr** [comment]
Thank you for your answer. If it'll come with the ES6 classes, I agree, let's forget it then.

**Comment by dwickern** [comment]
Have you looked into using ember-cli-typescript at all?

<img width="577" alt="Screen Shot 2019-04-09 at 9 52 58 AM" src="https://user-images.githubusercontent.com/752885/55819276-4a114a80-5aad-11e9-99c7-4626ddf6aec9.png">

**Comment by JulienFr** [comment]
Thank you ! I'll do that.
I am using Typescript with Angular in parallel, but did not make the link betweeen Typescript and Ember.
