### ISSUE TITLE
In the latest WebStorm EAP 2019.3 EAP ember run configurations are missed

### ISSUE THREAD

**Issue by anstarovoyt** [Turbo87/intellij-emberjs#276]
In the latest WebStorm EAP after installing Ember plugin both Ember Run configurations (Serve & Test) are missed.
WebStorm 2019.3 EAP
Build #WS-193.4932.10, built on October 30, 2019
WebStorm EAP User
Expiration date: November 29, 2019
Runtime version: 11.0.4+10-b520.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: documentation.show.toolbar=true, java.completion.argument.hints.internal=false, debugger.valueTooltipAutoShowOnSelection=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.emberjs, com.intellij.lang.jsgraphql, quokka.js

А! No exception in logs :(

**Comment by Turbo87** [comment]
thanks for reporting this @anstarovoyt! any clue what might be going on that could cause this?

**Comment by Turbo87** [comment]
I assume that this is a similar issue to https://github.com/Turbo87/intellij-emberjs/issues/302, and very likely with a similar resolution. Unfortunately I don't seem to be able to remove those old plugin versions from the store, which would remove the confusion 😞
