### ISSUE TITLE
Add possibility to disable JSHint

### ISSUE THREAD

**Issue by rogatty** [Turbo87/intellij-emberjs#28]
In our project we use ESLint, so there is no need for JSHint inspection. Yet, every time I open WebStorm 11 and a JS file, I see a red bar in editor window saying:
>JSHint config not found

I tried unchecking "Enable" field in JSHint settings and disabling its inspection but it's back after restarting WebStorm.

Is it possible to have a way to disable it for good?

**Comment by Turbo87** [comment]
@rogatty are we talking about an Ember project or another type of project? does your project still have a `.jshintrc` file?

**Comment by rogatty** [comment]
It's a mixed project, where the Ember part resides in a subdirectory (`/front/main`). All features work without any issues so I guess it's not a problem. There is no `.jshintrc` file neither in root nor in Ember directory.

If you want to take a look at the structure there it is: https://github.com/Wikia/mercury

**Comment by Turbo87** [comment]
thanks for the repo link, that'll be helpful for testing any potential fixes. I guess I could change the algorithm to only active JSHint if the corresponding file exists.

**Comment by rogatty** [comment]
That would be great, thanks :)

**Comment by rogatty** [comment]
Works great, thank you @Turbo87!
