### ISSUE TITLE
Dasherized model names CTRL-Click not working

### ISSUE THREAD

**Issue by drewclauson** [Turbo87/intellij-emberjs#3]
First, thanks for this!  Been looking awhile for something like this to come out!

I found that if I have a dasherized model like `customer-location`, when I CTRL-Click on the `belongsTo` in a related model, it doesn't link to the model.  It does link to non-dasherized correctly, however.

```
let {Model, attr, belongsTo} = DS;

export default Model.extend({
//...
    location: belongsTo('customer-location')
//...
});
```

**Comment by Turbo87** [comment]
> It does link to non-dasherized correctly, however.

I am very surprised by that because I haven't knowingly written any code that does that :smile:

**Comment by drewclauson** [comment]
Interesting - you know I just noticed that instead of linking directly, it simply brings up an autocomplete window that shows implementations of the name of that.  So, it gives me the option to link to models/customer.js or any other model that has a `customer:` property...

![image](https://cloud.githubusercontent.com/assets/10655807/11533377/4b8fdb7e-98d7-11e5-93aa-a2e342821da3.png)

**Comment by drewclauson** [comment]
Linking directly would be fun, though. :smile:

**Comment by Turbo87** [comment]
```js
crate: DS.belongsTo('crate')
```

<kbd>ctrl</kbd>-clicking on `'crate'` basically just links to the `crate` property itself instead of the `crate` model for me. It looks like this is something that the IntelliJ JavaScript plugin does internally for cases where you use e.g. `someObject['someKey']`. It might be possible to hook into that, but it doesn't look like  it's meant to be extended in such a way.

Feel free to work on this and I'd be happy to review and merge any pull requests, but I'm unlikely to work on this myself in the foreseeable future.

**Comment by drewclauson** [comment]
Thanks, I'll take a look into it at some point, but I'm not very familiar with the code at this point. Thanks again for working on this!

**Comment by Turbo87** [comment]
I wouldn't say I'm particularly familiar with it either. Unfortunately the IntelliJ JavaScript plugin is closed source and even the open source parts of IntelliJ aren't that well documented. I'm quite surprised actually by how much of it I've figured out already :wink:

**Comment by Turbo87** [comment]
I'm reopening this because I may have found a way to implement it...

**Comment by Turbo87** [comment]
resolved by 78b354c

**Comment by drewclauson** [comment]
I tried building this from source, but maybe I did something wrong, I can't seem to make it work any different than it did before.  I should have been pulling from master, correct?

**Comment by Turbo87** [comment]
yes, the master branch includes this feature. if you have at least Java 1.7 all you should need to do is `./gradlew runIdea`.

**Comment by drewclauson** [comment]
Part of the problem could be that I'm on Windows, but I'm not sure.  I'm actually using PHPStorm, but I installed IntelliJ IDEA 15.0.1 evaluation and here's what I get when I control click `'customer'`.  I confirmed that the customer model is located at  /app/models/customer.js  Looks like the Javascript plugin is still overriding it.  Will try it without the JS plugin.

![image](https://cloud.githubusercontent.com/assets/10655807/11563995/ba2adaac-99a4-11e5-84d0-88fb8bc1ee2e.png)

**Comment by drewclauson** [comment]
FYI, I import belongsTo in `let {Model, attr, hasMany, belongsTo} = DS;` but was checking to see if adding the DS at the beginning was a factor.

**Comment by drewclauson** [comment]
Never mind on trying without JS support, Ember.js relies on it. whoops :innocent:

**Comment by Turbo87** [comment]
hmm I guess the "on Windows" part *might* be a problem. I'm developing this plugin on OSX and haven't tested it on Windows yet.

The destructuring import shouldn't be a problem because it only matches on the last part of the method name (i.e. `belongsTo`). It will only fail if you alias the function with another name.

**Comment by Turbo87** [comment]
I've just tried this with the current master (6b76e10) inside a Windows 7 VM and it works just fine for the https://github.com/rust-lang/crates.io repo. 

Could you try to reimport the project? I've implemented this feature in a way that it only works on Ember.js modules and if your module/project somehow is not an Ember.js module/project it won't work.

**Comment by drewclauson** [comment]
I cloned crates and this is what I get... (tooltip is "Multiple Implementations")

![image](https://cloud.githubusercontent.com/assets/10655807/11570953/f238e4f2-99c7-11e5-996c-48d6d68b8240.png)

**Comment by drewclauson** [comment]
Wait... I just realized what you meant by reimport - just a sec

**Comment by drewclauson** [comment]
Reimporting the project did it!  Windows 10, 64-bit running PHPStorm 10.0.1 64-bit, FYI

**Comment by Turbo87** [comment]
awesome, thanks for debugging this. what did you previously think when I said reimport?

**Comment by drewclauson** [comment]
For whatever reason I thought invalidate the cached files... Just one of those days :wink:

**Comment by drewclauson** [comment]
Side question: when autocompleting a hasMany or belongsTo entity, is it supposed to automatically pop up with suggested model names or do I have to hit ctrl-space every time?  I am getting it to pop up only when hitting ctrl-space.

**Comment by drewclauson** [comment]
Btw, love the icons!

**Comment by Turbo87** [comment]
It only work with ctrl-space for now. The icons are imported from the font-awesome project, but I'm not sure if they'll stay like this. I just needed to display *something* instead of emptiness for now.

**Comment by drewclauson** [comment]
> I just needed to display something instead of emptiness for now.
:+1: :+1:
