### ISSUE TITLE
Template lint warning a bit too aggressive?

### ISSUE THREAD

**Issue by mydea** [Turbo87/intellij-emberjs#300]
### Description

The new template lint integration is pretty cool! However, I found it to maybe be a bit too aggressive. I now constantly get a big red error bar on top saying "TemplateLint: templateLint result parsing error" while typing, e.g. when opening a new curly brace. It goes away when I close the curly brace, but it is a bit disorienting as it happens all the time. IMHO the red warning should not be shown immediately (or at all?) if it cannot parse a valid HBS file.

### Steps to Reproduce

1. Create a new .hbs file
2. Start typing e.g. `{{` - you get the red error bar on top
3. Complete the expression (e.g. `{{log 'test'}}`) and it goes away

**Expected behavior:** No error should be shown when I start typing in the template

**Actual behavior:** An error is shown immediately

**Reproduces how often:** 100%

**Comment by makepanic** [comment]
I think we can easily :tm: fix this. I'll look into it later, thanks for the report.
