### ISSUE TITLE
No Ember.js run/debug configuration templates in WebStorm 2020.1 EAP

### ISSUE THREAD

**Issue by viktoria-shirunova** [Turbo87/intellij-emberjs#302]
### Steps to Reproduce

- run WebStorm 2020.1 EAP
- install `Ember.js` plugin from marketplace
- create any project
- open `Run/Debug Configurations` dialog, check list of templates:
expected: templates `Ember Serve` and `Ember Test` are present
actual: they are absent.

At that there are no exceptions.

### Versions

WebStorm 2020.1 EAP
Build #WS-201.5259.16, built on February 13, 2020
WebStorm EAP User
Expiration date: March 14, 2020
Runtime version: 11.0.6+8-b722.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 8
Registry: 
Non-Bundled Plugins: com.emberjs

Ember.js version: 2016.2.4-0

### Additional Information
the similar issue https://github.com/Turbo87/intellij-emberjs/issues/276 was fixed in the WebStorm 2019.3 release.

**Comment by Mifrill** [comment]
Same for me with WebStorm 2020.3 / Ember.js Plugin 2016.2.4-0, @Turbo87 any update here?

**Comment by Turbo87** [comment]
the v2016 version of this plugin doesn't have that functionality. there is no officially compatible release for WebStorm 2020.3 yet, since our test suite is currently failing on that version.
