### ISSUE TITLE
Question: Undo previously suppressed inspection rule

### ISSUE THREAD

**Issue by Subaku** [Turbo87/intellij-emberjs#303]
Hi, 

I have a problem were I told PyCharm to suppress an inspection rule but later decided I wanted it back. How can I do that? I'm not seeing anything for this in any files or PyCharm's inspection views in preferences. 

Specifically the rule is `ember/use-brace-expansion`

Thanks!

**Comment by Turbo87** [comment]
sorry, I don't know how to answer this either. the `ember/use-bracee-expansion` is an ESLint rul that is unrelated to this IntelliJ/PyCharm plugin. you would have to look at the docs for the ESLint plugin for PyCharm.
