### ISSUE TITLE
Automatically enable IntelliJ EAPs

### ISSUE THREAD

**Issue by vlascik** [Turbo87/intellij-emberjs#305]
Currently, the plugin doesn't work on EAPs. It's possible to enable plugins to also work on EAPs automatically though:

https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html

currently `plugin.xml` contains following line: 
```
<idea-version since-build="193" until-build="193.*"/>
```

According to https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000620084-how-to-build-a-plugin-that-is-compatible-to-multiple-versions-of-IntelliJ- and
https://github.com/JetBrains/gradle-intellij-plugin/blob/master/README.md, this can be manipulated at build time via gradle task `patchPluginXml`: 

```
patchPluginXml {
    sinceBuild '193'
    untilBuild '201'
}
```

This might also be the underlying reason for several other reported EAP issues in this repo.

**Comment by Turbo87** [comment]
I'd rather not do that, because we can't guarantee that the old versions actually will work on the EAP releases.

**Comment by vlascik** [comment]
Well, I guess that's your prerogative, but I'll just try to explain why it might be a better idea to try to list EAP versions anyway:

- Noone expects EAP versions to work. People using EAPs usually expect breakages and can fall back.
- By not adding EAP to the manifest, you just ensure that the plugin doesn't work even if it could.
- Instead of receiving a 3-4 month early warning the plugin will just stop working on the day of the new stable release, as it just happened again with 2020.3, and you'll have to scramble to fix it ASAP instead of fixing it over a period of several months.

Adding EAPs to the manifest might actually help you as a maintainer too.

**Comment by Turbo87** [comment]
> Instead of receiving a 3-4 month early warning the plugin will just stop working on the day of the new stable release, as it just happened again with 2020.3, and you'll have to scramble to fix it ASAP instead of fixing it over a period of several months.

there is nothing stopping us from having a version out there that works with those EAP versions, but it won't be the same one that also works for the stable version. we've already had that in the past.

> as it just happened again with 2020.3

this was caused by the test suite failing to run properly when upgrading to 2020.3 (or any of the previous EAPs), and it simply took a while to figure out what the problem was. feel free to open a PR to update us to the next EAP when it comes out, then this whole process would certainly be faster 😉

**Comment by vlascik** [comment]
> there is nothing stopping us from having a version out there that works with those EAP versions, but it won't be the same one that also works for the stable version. we've already had that in the past.

Whichever you prefer, two JARs are fine too.

> this was caused by the test suite failing to run properly when upgrading to 2020.3 (or any of the previous EAPs), and it simply took a while to figure out what the problem was. feel free to open a PR to update us to the next EAP when it comes out, then this whole process would certainly be faster 😉

Yeah, if it only was so simple. I could count the hours of my experience with IDEA SDK on one hand, what would take regular contributors 30 minutes to set up might take me days. Don't think PRs are realistic anytime soon, the knowledge gap is just too wide.

Well, I hope you'll reconsider anyway.
