### ISSUE TITLE
Support WebStorm 2020.1

### ISSUE THREAD

**Issue by Vinccool96** [Turbo87/intellij-emberjs#309]
### Description

Webstorm 2020.1 has been released today. It should be supported.

**Comment by 7934345** [comment]
Error Message: Plugin Error: Plugin "Ember.js" is incompatible (until build 193.SNAPSHOT < WS-201.6668.106).

**Comment by Turbo87** [comment]
PRs welcome 😉

**Comment by Vinccool96** [comment]
Only need to publish now. Thanks!
