### ISSUE TITLE
JavaScript language version is decreased to ECMAScript6+

### ISSUE THREAD

**Issue by ulitink** [Turbo87/intellij-emberjs#329]
### Description

Upon opening a project having React JSX or Flow language version configured, it's dropped to ECMAScript6+. Please see reported issue in WebStorm tracker: [WEB-47463](https://youtrack.jetbrains.com/issue/WEB-47463).

The problem is in [EmberCliProjectConfigurator.kt](https://github.com/Turbo87/intellij-emberjs/blob/27d45ad1b50f1f1476b9cd50f07abac77e32bca2/src/main/kotlin/com/emberjs/cli/EmberCliProjectConfigurator.kt), `setES6LanguageLevel` function should check current language version before updating it, e.g.
```
        private fun setES6LanguageLevel(project: Project) {
            JSRootConfiguration.getInstance(project)?.apply {
                if (!getLanguageLevel().isES6Compatible()) {
                  storeLanguageLevelAndUpdateCaches(JSLanguageLevel.ES6)
                }
            }
        }
```

**Comment by Turbo87** [comment]
PR welcome 😉
