### ISSUE TITLE
Ember-cli editor documentation

### ISSUE THREAD

**Issue by kgish** [Turbo87/intellij-emberjs#34]
On the Ember-cli website under [Editors](http://ember-cli.com/user-guide/#editors), I've included a section for setting up WebStorm.

Wouldn't it be nice if you could also have a link for this plugin put there?

**Comment by Turbo87** [comment]
sure, that would be awesome. could you put it on there?

**Comment by kgish** [comment]
Done. Hopefully my push request will be accepted soon.

https://github.com/ember-cli/ember-cli.github.io/pull/42

**Comment by Turbo87** [comment]
already accepted. great, thanks!
