### ISSUE TITLE
Javascript import

### ISSUE THREAD

**Issue by drewclauson** [Turbo87/intellij-emberjs#35]
Consider this at the beginning of a controller:

```
import AwesomeMixin from 'my-cool-project/mixins/awesome-mixin';
```

When calling `this.runMethod()`, the IDE doesn't recognize the import, so `runMethod` gets a "unresolved function or method" warning.

Is there a way to support this through the plugin or am I missing a configuration setting in my IDE?  I have set the package prefix for the app folder to 'my-cool-project' in the Project Directory settings, but that doesn't seem to do it.

Thanks!

**Comment by Turbo87** [comment]
I haven't figured that out either. It might be possible, but I really have no clue how. Please let me know if you find a way to make this work.

**Comment by drewclauson** [comment]
I'll try to dive into it this week, thanks!

**Comment by dwickern** [comment]
Does it work with a relative import like `import AwesomeMixin from '../mixins/awesome-mixin';` ? I don't think intellij understands what `my-cool-project` is

**Comment by Turbo87** [comment]
@dwickern yes, relative imports should be resolved by IntelliJ automatically

**Comment by AndriusZid** [comment]
Hi, @Turbo87,
I also have issue with "unresolved function or method" but it is test files when importing "qunit" module. All ember-testing helpers are unresolved like andThen and findWithAssert methods which are defined in node_modules directory somewhere. Is it possible to resolve those methods and make them work with auto-completion?

Thanks

**Comment by Turbo87** [comment]
@AndriusZid I'm not aware of any solution for this right now. I'm using Mocha instead of QUnit, but that's just personal preference.

**Comment by Turbo87** [comment]
for reference: https://youtrack.jetbrains.com/issue/WEB-21959
