### ISSUE TITLE
Not compatible with 2020.3 releases (yet)

### ISSUE THREAD

**Issue by m-harnish** [Turbo87/intellij-emberjs#354]
The latest Rubymine (2020.3 at this time) only supports up to version 2016.2.4-0 of the emberjs plugin.

If I try to install the latest version manually (via Install Plugin from Disk), it gives the following error:

<img width="406" alt="Error_and_Preferences" src="https://user-images.githubusercontent.com/17304065/101938922-10a1b400-3b99-11eb-8cb0-708a0d9f6563.png">

**Comment by Turbo87** [comment]
yep, unfortunately our test suite is currently failing when run with IntelliJ 2020.3 and I haven't have time yet to figure out why that is and how it can be fixed. PRs to fix this are welcome :)

**Comment by robclancy** [comment]
I'd like to get involved with this plugin (or a new one, if this one is suffering from super old ember versions), are there any generic resources to get started with how intellij plugins work?  
And would it be worth trying to get the ember-language-server working?

**Comment by Turbo87** [comment]
> if this one is suffering from super old ember versions

idk what that means. the plugin is working fine with the most recent Ember versions.

> are there any generic resources to get started with how intellij plugins work?

if I remember correctly there are some docs on the JetBrains pages, but the API surface is huge and the docs only covers small parts of it unfortunately.



> And would it be worth trying to get the ember-language-server working?

would be worth investigating, but I'm a little afraid of it making the setup here even more complex 😅

**Comment by derekwsgray** [comment]
Ah this must explain why I don't see Ember  Run Configurations. I had (for my sanity) to upgrade to 2020.3 for a horrible mouse-focus bug they fixed on linux (webstorm). dang...

**Comment by Turbo87** [comment]
v2020.3.1 is on the way to the plugin store now 🎉

**Comment by m-harnish** [comment]
Awesome, the update works great! Thanks for creating and maintaining this plugin!
