### ISSUE TITLE
Extremely degraded typing performance when Ember.js plugin is installed and .hbs files are in focus

### ISSUE THREAD

**Issue by tristanbiesecker** [Turbo87/intellij-emberjs#360]
### Description

When a `.hbs` file is open *and visible* in Intellij (Ultimate), typing performance becomes quite choppy/laggy, including autocompletion. However, if the `.hbs` tab isn't focused, performance is normal.

For example, let's say I have a `.js` file open on the left (split view), and a `.hbs` file on the right. With this setup, I will experience laggy typing in both my `.js` file and my `.hbs` file. However, if I focus on another non-hbs tab (replacing the `.hbs` file) performance returns to normal. `.hbs` files, split or not, always have degraded performance though.

### Steps to Reproduce

1) Install Ember.js plugin
2) Open a `.hbs` file and type away

**Expected behavior:**
Typing to be smooth, along with autocompletion.

**Actual behavior:**
Typing becomes laggy, I would say up to 500ms per keyboard click sometimes before my input is reflected in the editor.

**Reproduces how often:**
100% of the time. However, I think this problem only occurs for **substantially large projects**. *Very interestingly*, however, this problem seemed to go away in one of the recent releases of Emberj.js, but is back for 2020.2.3-0.

### Versions

**IntelliJ version:**
IntelliJ IDEA 2020.3.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020

**Ember.js version:**
2020.3.2-0

**Comment by Turbo87** [comment]
thanks for the report. I'm wondering if there was some way to reproduce this problem. I do have a few somewhat larger projects that I regularly work on and I haven't experienced any issues like this yet.

**Comment by tristanbiesecker** [comment]
It's unclear to me how to reproduce the issue in a different project other than the one I'm working on. All I can definitively say is that if I uninstall Ember.js, `.hbs` performance is normal (albeit without all the bells and whistles Ember.js provides), and once I install it again, performance takes a hit. Unfortunately, my project is within my company's domain, so sharing more details won't really be possible.

Can you think of any diagnostics that might be useful for you?

Also, here are my custom **VM options**:
```
-Xms2g
-Xmx12g

-ea

-XX:NewRatio=3
-XX:MaxPermSize=2G
-XX:ReservedCodeCacheSize=2G
-XX:SoftRefLRUPolicyMSPerMB=50
-XX:CICompilerCount=2
-XX:ErrorFile=$USER_HOME/java_error_in_idea_%p.log
-XX:HeapDumpPath=$USER_HOME/java_error_in_idea.hprof
-XX:MetaspaceSize=1G
-XX:+UseConcMarkSweepGC
-XX:+UseCompressedOops
-XX:+UseCodeCacheFlushing
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow

-Dcaches.indexerThreadsCount=16
-Dfile.encoding=UTF-8
-Dsun.io.useCanonPrefixCache=false
-Djdk.http.auth.tunneling.disabledSchemes=""
-Djdk.attach.allowAttachSelf=true
-Djdk.module.illegalAccess.silent=true
-Dkotlinx.coroutines.debug=off
```

And **Custom Properties**:
```
editor.zero.latency.typing=true
idea.max.intellisense.filesize=20000
```

**Comment by Turbo87** [comment]
> Can you think of any diagnostics that might be useful for you?

I'm afraid I currently don't have any clue what might be causing this for you. Maybe you could clone the project locally and check if the same happens when using `./gradlew runIde` and if that happens to give any clues.

**Comment by tristanbiesecker** [comment]
Unfortunately, I have not been able to gather any further diagnostic information. Closing this out for now.
