### ISSUE TITLE
Navigation through components have broken in new WebStorm version

### ISSUE THREAD

**Issue by rogeraraujo90** [Turbo87/intellij-emberjs#382]
### Description

I've updated my WebStorm version to WebStorm 2021.2 and now the navigation through components is not working

### Steps to Reproduce

- I'm in a template
- I press "ctrl" and click on a Component tag

**Expected behavior:** [What you expect to happen]
- We should navigate to the component template

**Actual behavior:** [What actually happens]
- Nothing happens. WebStorm is not detecting the Component tag as a navigable link.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
WebStorm 2021.2
Build #WS-212.4746.80, built on July 23, 2021

- The version of `intellij-emberjs` (`Settings` -> `Plugins` -> `Ember.js`):
2016.2.4-0

### Additional Information

Looks like there is a bug in the Plugin version, or the new WebStorm version have changed the Plugin version to a very old one.

**Comment by nickschot** [comment]
Yeah it seems to have updated to a very old 2016 release as that specifies a minimum version only, and the latest version of the plugin isn't compatible with 2021.2 yet.

**Comment by loxmys** [comment]
Any ideas?

**Comment by Turbo87** [comment]
Yep, it needs a new release but I'm still on vacation until next week

**Comment by tristanbiesecker** [comment]
Something important that I noticed though is that with `2016.2.4-0` the issues I described in #360 are gone. Any thoughts as to why that might be the case @Turbo87?

**Comment by Turbo87** [comment]
Probably because it doesn't contain the problematic feature that is causing the issues for you

**Comment by tristanbiesecker** [comment]
> Probably because it doesn't contain the problematic feature that is causing the issues for you

Huh, I guess I couldn't have surmised that myself. 😒
