### ISSUE TITLE
Support pods structure for related symbol navigation in components

### ISSUE THREAD

**Issue by Ramblurr** [Turbo87/intellij-emberjs#39]
Using a pods structure on a project currently has inconsistent related symbol navigation support.

The navigation seems to work in top-level directories of pods like, 'pods/application' or 'pods/someotherthing'. But it does not work for components in 'pods/components/user-list' for example.

I'm not sure if this is a bug or a feature request.

```
Ember      : 2.3.1
Ember Data : 2.3.3
Ember CLI  : 2.3.0
```

**Comment by Turbo87** [comment]
do you have a repo somewhere to reproduce this?

**Comment by Ramblurr** [comment]
I can't seem to reproduce this anymore, I chalk it up to some indexing hijinks.
