### ISSUE TITLE
Plugin does not work in IDEs other than IntelliJ itself

### ISSUE THREAD

**Issue by orf** [Turbo87/intellij-emberjs#4]
Hey there, thanks for this plugin! I'm testing it out on my EmberJS project and it appears to not be detecting the app. My actual EmberJS project is inside a directory called 'frontend' (the project contains the backend code as well), so the app.js is located at 'frontend/app/app.js'. Any chance this could be picked up by the plugin?

**Comment by Turbo87** [comment]
I've been testing this by importing https://github.com/Turbo87/intellij-emberjs/tree/master/src/test/resources/com/emberjs/fixtures/nested-projects and it correctly picks up both projects as two separate Ember.js modules. 

Could you try this with the current master branch or v1.3.0? I've changed a few things regarding this lately and I'm not sure if v1.2.0 already handled this case correctly.

**Comment by orf** [comment]
Hi,
I've tried this with 1.3.0 but with no luck. I've even tried making a new project with no nested directories in PyCharm and the plugin still doesn't seem to trigger: All I do is `ember new test2` inside `~/PycharmProjects`, then open `~/PycharmProjects/test2` in PyCharm.

**Comment by Turbo87** [comment]
how do you "open" the project? you should use `File → New → Project from Existing Sources...` to properly import it.

**Comment by kitsunde** [comment]
PyCharm doesn't have `file -> new -> ..` I did do `file -> open..` On an existing project (i nuked the previous .idea) and I have the same issue.

**Comment by orf** [comment]
Hey @Turbo87, I was just making a new project, or doing `file -> open`. @kitsunde is right though, there doesn't seem to be a `New project from existing sources` option. It would be really awesome if you could perhaps add a 'mark as EmberJS' option to the right-click context menu, or maybe to the settings panel?

**Comment by Turbo87** [comment]
hmm... interesting, I thought the IDEs were mostly similar in that regard... I don't have a PyCharm license, but I'll try to figure this out in some way.

**Comment by Turbo87** [comment]
So it looks like PyCharm is opening projects significantly different from what IntelliJ does. This might not be as easy to resolve as I hoped. I might be able to make some features work by removing the Ember.js module restriction, but I'm not sure yet if that is really the right way to go here...

**Comment by Turbo87** [comment]
@orf @kitsunde just as a heads up: I'm going on vacation next monday for a few weeks and won't be able to work on this project until I get back. I'll try to fix this issue until then, but I can't promise anything yet. Feel free to help out and experiment with the code though, I'd be happy to merge any pull requests!

**Comment by Turbo87** [comment]
@orf @kitsunde okay, I think I've got it working now. it's not perfect yet, but most of the functionality seems to work fine. please check out the [project-roots](https://github.com/Turbo87/intellij-emberjs/tree/project-roots) branch, build the plugin, install it via zip file and test whether that works for you!

marking the project as ES6 and marking the folders is not implemented yet, but goto class, goto related, icons, etc. should work fine. please let me know if it works!

**Comment by Turbo87** [comment]
I have just release v1.3.1 and it should hopefully fix the problem.

**Comment by orf** [comment]
Hi, sorry about the lack of feedback! Things got a bit hectic here.

It seems to work fine, thanks so much! Marking the `node_modules` and `bower_components` still doesn't seem to work, but the introspection stuff (which is amazing) works fine! Thanks again :+1:

**Comment by Turbo87** [comment]
@orf good to hear, thanks!
