### ISSUE TITLE
"Worker exited due to exception: it.virtualFile must not be null"

### ISSUE THREAD

**Issue by k3n** [Turbo87/intellij-emberjs#40]
I'm getting the above error message multiple times a day, and I'm on:

> WebStorm WS-144.3891.13
> Build #WS-144.3891, built on February 10, 2016
> JRE: 1.8.0_40-release-b128 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

My Ember version is `1.10.1`.

I'm not sure what's triggering it, and I'm not aware of what the implications are -- I just notice the flashing error icon in WebStorm pretty often.

Please let me know if you need more information.

**Comment by Turbo87** [comment]
@k3n please update your "Ember.js" plugin. this problem was fixed earlier today. (see #37)
