### ISSUE TITLE
Template Lint v4 no longer supports `--json` parameter

### ISSUE THREAD

**Issue by kategengler** [Turbo87/intellij-emberjs#428]
### Description

`ember-template-lint` 4.x no longer supports `--json` and has replaced it with `--format=json` See https://github.com/ember-template-lint/ember-template-lint/pull/2193

https://github.com/Turbo87/intellij-emberjs/blob/4d5c4e52e155f40d4e27bd43351fc3d5547790dc/src/main/kotlin/com/emberjs/hbs/linter/ember-template-lint/TemplateLintExternalRunner.kt#L115 seems to be this line that adds the param

**Comment by silverbucket** [comment]
I'm running into this as well

**Comment by arthur5005** [comment]
any workarounds? or is this hardcoded?
