### ISSUE TITLE
Plugin automatically creates "library roots" which kill performance

### ISSUE THREAD

**Issue by k3n** [Turbo87/intellij-emberjs#43]
Greetings,

After a long [debugging session with JetBrains' support](https://youtrack.jetbrains.com/issue/WEB-20199), we've deduced that this plugin is creating library roots out of my projects `node_modules` and `bower_components` directories. I'm not sure what features this powers within the plugin, but it makes performance in any non-trivial project completely unusable.

I can try to provide as much information as I can on request, though I'm not sure what might be relevant at this time. I have a very complex Ember 1.x app (we're in the process of updating!), and would like to use this plugin, but I simply can't in its current state.

**Comment by Turbo87** [comment]
@k3n this sounds like a duplicate of #24

**Comment by k3n** [comment]
Yup! Thanks, I'll close this one in favor of that one.

**Comment by Turbo87** [comment]
@k3n if you got a bit of time feel free to help with #24

**Comment by k3n** [comment]
I left a comment, but I'm not sure what else I can offer -- I'm still pretty green to Ember, and have never done any Idea plugin work.
