### ISSUE TITLE
How to fire up 'ember generate'?

### ISSUE THREAD

**Issue by larryh** [Turbo87/intellij-emberjs#44]
I hate to ask this, but how do you fire up the "ember > generate" dbox from within RubyMine?

I've looked all through the menus and could not find an "ember" anywhere.

I did a Ctrl-Shift-a to bring up the "Enter Action" dbox, but when I type "ember" or "ember generate" nothing happens. 

Specifically, when I type "ember" a bunch of options appear in a drop-down. The first one is "Ember.js files", but that is disabled => nothing happens when you select it.

When I type "ember generate" RM fires up the Settings dbox with the "Plugins > Ember.js" entry selected.

I cannot get the dbox with the drop-down "Kind:" as illustrated in your main page.

Thanks,
Larry

**Comment by larryh** [comment]
Well, now when I when I fire up the RM "Enter Action" dbox and type "ember" the "Ember.js files" entry is enabled and the dbox comes up.

Beats me...

**Comment by larryh** [comment]
And now it's no longer working. The "Ember.js files" entry is disabled.

Like I said: beats me.

**Comment by Turbo87** [comment]
The way it works is right clicking on a folder and adding the file from there.

**Comment by larryh** [comment]
Thanks. (Sorry I didn't get that.) And thanks for the plug-in!
