### ISSUE TITLE
LineMarkerInfo deprecated for rubymine 2022.2

### ISSUE THREAD

**Issue by mathieusanchez** [Turbo87/intellij-emberjs#451]
### Steps to Reproduce

I don't really know how to reproduce, it seems to happen when RubyMine start.

**Expected behavior:** No error

**Actual behavior:** Getting an error message at each RubyMine start

### Versions

RubyMine 2022.2
Build #RM-222.3345.111, built on July 25, 2022

Ember.js plugin: 2016.1.4-0

### Additional Information

None

**Comment by Turbo87** [comment]
v2016.1.4 of the plugin is not meant to be used with v2022.2 of RubyMine. you might want to wait until we've released a version that is compatible :)

**Comment by Turbo87** [comment]
fixed by https://github.com/Turbo87/intellij-emberjs/releases/tag/v2022.2.1
