### ISSUE TITLE
Function helper invocation gets flagged incorrectly as an error

### ISSUE THREAD

**Issue by Alonski** [Turbo87/intellij-emberjs#454]
### Description

It is possible today to use functions as helpers in templates without any special invocation like this:
```hbs
{{(this.myCustomHelper @someArg)}}
```

However this shows up as an error in Webstorm.
```
Expected a path, String, Number, Boolean or @data
Expected Close "}}"
```

This code does actually work during runtime.

Example of this:
[Limber](https://limber.glimdown.com/edit?format=glimdown&t=%23%20Effects%20in%20Ember%0A%0AI%20don%27t%20have%20any%20valid%20use%20cases%20for%20effects%20that%20can%20fit%20in%20tiny%20demos%2C%20so%20I%27m%20just%20logging%20to%20the%20console%20when%20each%20effect%20function%20is%20called.%0A%0AWhen%20observing%20the%20behavior%20of%20these%20demos%2C%20be%20sure%20to%20have%20the%20browser%20console%20open.%0A%0A%23%23%20Layout%20Effect%0A%0ARun%20some%20code%20during%20initial%20render%0A%60%60%60gjs%20live%20preview%0Aconst%20myEffect%20%3D%20%28%29%20%3D%3E%20console.log%28%27runs%20once%27%29%3B%0A%0A%3Ctemplate%3E%0A%20%20%7B%7B%20%28myEffect%29%20%7D%7D%0A%3C%2Ftemplate%3E%0A%60%60%60%0A%0A%23%23%20Effect%20when%20arguments%20change%0A%0AIn%20ember%2C%20you%20usually%20don%27t%20need%20to%20do%20this%0Abecause%20derived%20data%20patterns%20have%20usually%20got%20covered%0A%28getters%2C%20resources%2C%20etc%29.%0A%0A%60%60%60gjs%20live%20preview%0Aimport%20state%20from%20%27limber%2Fhelpers%2Fstate%27%3B%0Aimport%20%7B%20on%20%7D%20from%20%27%40ember%2Fmodifier%27%3B%0A%0Aconst%20myEffect%20%3D%20%28foo%29%20%3D%3E%20console.log%28%27foo%20is%20now%20%27%2C%20foo%29%3B%0A%0Aconst%20WithEffect%20%3D%20%3Ctemplate%3E%0A%20%20%7B%7B%20%28myEffect%20%40foo%29%7D%7D%0A%3C%2Ftemplate%3E%3B%0A%0A%3Ctemplate%3E%0A%20%20%7B%7B%23let%20%28state%29%20as%20%7Cs%7C%7D%7D%0A%20%20%20%20%3Cinput%20%7B%7Bon%20%27input%27%20s.increment%7D%7D%20class%3D%22border%22%20%2F%3E%0A%20%20%20%20%3CWithEffect%20%40foo%3D%7B%7Bs.value%7D%7D%20%2F%3E%0A%20%20%7B%7B%2Flet%7D%7D%0A%3C%2Ftemplate%3E%0A%60%60%60%0A%0A%23%23%20Effects%20auto-track%0A%0AIf%20accessing%20tracked%20data%20within%20a%20function%20or%20effect%2C%20%0Ait%20will%20auto-track%2C%20and%20re-run%20when%20the%20tracked%20data%20changes.%0A%0A%60%60%60gjs%20live%0Aimport%20Component%20from%20%27%40glimmer%2Fcomponent%27%3B%0Aimport%20%7B%20on%20%7D%20from%20%27%40ember%2Fmodifier%27%3B%0Aimport%20%7B%20tracked%20%7D%20from%20%27%40glimmer%2Ftracking%27%3B%0A%0Aexport%20default%20class%20Demo%20extends%20Component%20%7B%0A%20%20%40tracked%20value%3B%0A%20%20%0A%20%20myEffect%20%3D%20%28%29%20%3D%3E%20%7B%0A%20%20%20%20console.log%28%60tracked%20value%3A%20%24%7Bthis.value%7D%60%29%3B%0A%20%20%7D%0A%0A%20%20update%20%3D%20%28event%29%20%3D%3E%20this.value%20%3D%20event.target.value%3B%0A%20%20%0A%20%20%3Ctemplate%3E%0A%20%20%20%20%7B%7B%20%28this.myEffect%29%20%7D%7D%0A%0A%20%20%20%20%3Cinput%20%7B%7Bon%20%27input%27%20this.update%7D%7D%20class%3D%22border%22%20%2F%3E%0A%20%20%3C%2Ftemplate%3E%0A%7D%0A%60%60%60)

### Steps to Reproduce

Add this to a template:
```hbs
<div {{(this.myFunc @someArg)}}></div>
```

**Expected behavior:** No errors are shown

**Actual behavior:** Two errors are shown

**Reproduces how often:** 100%

### Versions

- The first two lines of the `Help` -> `About` output:
WebStorm 2022.2
Build #WS-222.3345.108, built on July 22, 2022

- The version of `intellij-emberjs` (`Settings` -> `Plugins` -> `Ember.js`):

2022.2.1

### Additional Information

Other than being visually annoying this isn't impacting anything.

**Comment by Turbo87** [comment]
you should report this to the maintainers of https://plugins.jetbrains.com/plugin/6884-handlebars-mustache. I'm just handling the Ember.js specific things in this plugin, but I'm not doing the parsing of Handlebars etc.

**Comment by Alonski** [comment]
Ok thanks. Will do that
