### ISSUE TITLE
Cannot run program "./node_modules/.bin/ember"

### ISSUE THREAD

**Issue by chriskrycho** [Turbo87/intellij-emberjs#47]
Whenever I try to run the Ember commands, I get the following error:

```
Problem running ember-cli:
Cannot run program "./node_modules/.bin/ember": error=2, No such file or directory
```

Ember-CLI works fine from the command line (including running exactly that command). Might be a configuration error on my end; happy to provide more details to help suss out the cause.

**Comment by Turbo87** [comment]
@chriskrycho on which platform are you running this? is this similar to #46?

**Comment by larryh** [comment]
Hi,

I just experienced the same problem. It does appear to be similar to #46, except I am not running on Windows.

Platform: Ubuntu 15.10 and RubyMine 2016.1

BTW, your plugin was working awhile ago. I just upgraded ember-cli to 2.4.3 (from 2.4.2, I believe). Maybe that has something to do with it.

-- Larry
-- Larry

**Comment by chriskrycho** [comment]
Sorry for the delay, @Turbo87; busy couple days. Currently config:

- OS X 10.11.4
    - Ember CLI 2.4.2
    - Node 5.9.0
    - IntelliJ IDEA 2016.1.1
        - Ember.js plugin (this) 1.5.0

**Comment by nikdojo** [comment]
Hey man!
Same here:

- OSX 10.11.4
- WebStorm 2016.1.1
- Ember-cli 2.4.3

**Comment by arcaynus** [comment]
I am in the same boat, I am using:

- OSX 10.11.4 
- PHP Storm 2016.1.1
- Ember-cli 2.4.3

It does not seem like after running npm install -g ember-cli on the command line put ember in the location the plugin is looking for.  Command line works fine.

**Comment by Turbo87** [comment]
@chriskrycho it seems that this broken with 38c7de67f3139ffde2ce3a6cf02b1257cc08977c, but I'm currently pretty clueless *why* it broke...

**Comment by Turbo87** [comment]
@chriskrycho looks like the issue you're running into will be solved by https://github.com/Turbo87/intellij-emberjs/commit/f7086730899732d40b1d6e0fc9bd10ade87d610e and #48
