### ISSUE TITLE
Java detection seems to override Ember.js

### ISSUE THREAD

**Issue by Ramblurr** [Turbo87/intellij-emberjs#5]
I've a ember-cli app with the ember-cli-cordova addon. This addon makes a cordova folder with lots of stuff in it.

Some of this stuff is Java for Cordova's android support.

When I attempt to import my ember project in IDEA via `File → New → Project from Existing Sources...`, after scanning the folders, it shows the cordova Java files:

![import_project](https://cloud.githubusercontent.com/assets/14830/11624603/4743af58-9cd5-11e5-93b4-e575987e3fd7.png)

If I temporarily remove the cordova folder, then IDEA detects my project as expected:

![idea-ember-create](https://cloud.githubusercontent.com/assets/14830/11624611/545fa368-9cd5-11e5-898a-d37f440c2ba1.png)

**Comment by Turbo87** [comment]
@Ramblurr could you make an example project with that issue that I can clone?

**Comment by panthony** [comment]
Same issue here.

I have an application with "ember-suave".

If I do "npm installl" then try to import the project then it will try to create a java project with the following directory as source:

./node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/node_modules/jsonlint/node_modules/JSV/jsdoc-toolkit/java

If I remove node_modules folder before trying to import the project then it will correctly detect my ember application.

**Comment by Turbo87** [comment]
This is actually related to #4. Apparently this whole module detection thing is only available on IntelliJ and according to this ticket even there it doesn't work 100% reliably. We need to find a better solution for this, but so far I haven't found one.
