### ISSUE TITLE
Compatibility to version 2023.3

### ISSUE THREAD

**Issue by vaxul** [Turbo87/intellij-emberjs#500]
> Plugin 'Ember.js' (version '2023.2.1') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is PS-233.11799.232

I would appreciate, if someone would update this plugin, please. :) Thanks

**Comment by Turbo87** [comment]
PRs are welcome 😉

**Comment by vaxul** [comment]
Unfortunately, I have no idea about the plugin development for Jetbrains IDEs.
