### ISSUE TITLE
"Choose Target" menu in related symbols after upgrade to WebStorm 2016.1.1

### ISSUE THREAD

**Issue by pongo** [Turbo87/intellij-emberjs#51]
"Choose Target" menu appears when I select Navigate → Related symbol:

![2016-04-18_223236](https://cloud.githubusercontent.com/assets/142528/14617081/932d73a6-05b5-11e6-9625-faa21259f8f3.png)

Before upgrade to 2016.1.1 switching was instantly, without "choose target"

**Comment by Turbo87** [comment]
I'm not quite sure yet what's happening there, but I'm seeing the same problem in IntelliJ 2016.

**Comment by Turbo87** [comment]
@denofevil got a few seconds to explain what happened to this feature in 2016.1? are we misusing the [Related Symbol](https://github.com/Turbo87/intellij-emberjs/blob/master/doc/features.md#navigate--related-symbol) feature in this plugin or is this expected behavior?

**Comment by denofevil** [comment]
@Turbo87 I think that's expected behaviour. If there's more than one related for given context symbol popup will be shown. Here's the example from RubyMine, go to related symbol is called in Rails controller
<img width="378" alt="screen shot 2016-09-12 at 17 23 34" src="https://cloud.githubusercontent.com/assets/32124/18439364/0e9673fc-7916-11e6-8704-02d7a73c0a72.png">

**Comment by Turbo87** [comment]
Okay, that means that I haven't misunderstood the feature and everything is working correctly in the plugin. Do you know why the `Ember (order.js)` entry appeared in 2016.1? The plugin is providing the icon for the file, but it is not adding that related symbol there from what I can tell.

**Comment by denofevil** [comment]
@Turbo87 that's because I've added imported symbols to the related files for ES6)

**Comment by Turbo87** [comment]
okay, I guess that means there's not much we can do about it then. are the imported symbols supposed to use the icon of the containing file (`order.js` in this example)?
