### ISSUE TITLE
Tests appear before implementations in Navigate Class list

### ISSUE THREAD

**Issue by Ramblurr** [Turbo87/intellij-emberjs#52]
When using a pods structure, the tests for a route/controller etc appear before the actual implementation.

See this example:
![](https://cloud.githubusercontent.com/assets/14830/15670485/09525cf4-2726-11e6-91a3-5927dafca489.png)

It would be nice if the tests appeared last in the list.

**Comment by Turbo87** [comment]
I think this is related to the pods prefix thing. Since pods are essentially deprecated and will be replaced with the module unification RFC I won't put a lot of energy into this, but I'd be happy to review and merge any solutions to this problem.

**Comment by Ramblurr** [comment]
Sounds good, waiting until the new module rfc lands is fine with me.
