### ISSUE TITLE
Plugin doesn't seem to work with multiple modules

### ISSUE THREAD

**Issue by svyatogor** [Turbo87/intellij-emberjs#53]
Hi! I am not sure if I am doing it right, in which case please correct me. I have a project which consists of a few ruby services and a couple of emberjs apps. So I decided to add those as module to an empty IntelliJ project. I go to Project Structure, Add > Import module. The module is correctly identified as EmberJS. But when added the app folder is not recognized as source root, neither are node_modules and bower_components and pretty much nothing works.  I want to note that if I open the folder as a separate project, rather than as module it will work just fine.

**Comment by Turbo87** [comment]
@svyatogor that is unfortunately one of those rare use cases that I haven't cared much about when developing this plugin. I'd be happy to review and merge any pull requests that solve the issue though.

**Comment by msmyers** [comment]
+1

I have 10 modules in one of my projects and always wondered why the plugin was kick-ass in my solo module project but absent in my multi-module project.

Came here to find out why, and bam, it's the first issue.

**Comment by Turbo87** [comment]
any of you have an open source repo that shows the issue that you're talking about?
