### ISSUE TITLE
"esnext": true vs "esversion": 6,

### ISSUE THREAD

**Issue by basz** [Turbo87/intellij-emberjs#59]
Upgraded to ember-cli 2.7.0 and now I see warnings like;

'JSHINT let is available in es6 (use esnext option)'

whilst the upgrade options instructed me to replace `"esnext": true,` with `"esversion": 6,` in `.jshintrc`.

**Comment by Turbo87** [comment]
This is most likely not related to this plugin but to the jshint feature of intellij itself. You should probably open an issue on their bug tracker instead. Thanks for reporting though!
