### ISSUE TITLE
Poor visibility of icons on dark theme

### ISSUE THREAD

**Issue by panthony** [Turbo87/intellij-emberjs#7]
I use IntelliJ using the dracula theme and because pretty much all icons are black there is poorly visible:

![v57s7km](https://cloud.githubusercontent.com/assets/230462/11650066/deb57ffa-9d85-11e5-8d74-8c097b14b32a.png)

It would be nice to have icons that display better either on a dark or light theme.

Keep up the good work!

**Comment by Turbo87** [comment]
oh, totally forgot about darcula... should be an easy fix. feel free to try it yourself while I'm still busy on the other issues.

**Comment by panthony** [comment]
Will do :+1:

**Comment by Turbo87** [comment]
cool, thanks for helping out. If I remember correctly you just need to copy the icons, make them white and add a "dark"  suffix somewhere. check out the intellij-community repo for some examples.

**Comment by Turbo87** [comment]
fixed by 97a4e3d

**Comment by panthony** [comment]
You went ahead and fixed it :+1: 

I planned to take a look this week end since I'm very busy at the moment.

**Comment by Turbo87** [comment]
I wanted to release the update before the weekend because I'm going to be on vacation starting Monday.
