### ISSUE TITLE
executing ember server/test/run configs in intellij

### ISSUE THREAD

**Issue by pswenson** [Turbo87/intellij-emberjs#74]
Does this plugin facilitate  running ember server, tests, setting breakpoints, etc in IJ?

thanks

**Comment by Turbo87** [comment]
@pswenson you can run `ember serve` and `ember test` in IntelliJ, but so far this plugin doesn't have any special code that configures that for you. it looks roughly like this:

![bildschirmfoto 2016-09-29 um 09 33 59](https://cloud.githubusercontent.com/assets/141300/18944841/ea559d8c-8627-11e6-8213-4d5412bb10f5.png)
