### ISSUE TITLE
Tons of indexing

### ISSUE THREAD

**Issue by rwwagner90** [Turbo87/intellij-emberjs#76]
Could we mark bower_components and node_modules as excluded? Unsure if it indexes them as library root or not, but I get a ton of indexing for no reason all the time.

**Comment by Turbo87** [comment]
done 😉 

see https://github.com/Turbo87/intellij-emberjs/issues/24

**Comment by rwwagner90** [comment]
@Turbo87 if this is done, do you have any idea why indexing would be happening so much and for so long then?

**Comment by Turbo87** [comment]
@rwwagner90 you need to explicitly disable indexing of those folders in the plugin settings. Indexing them has some advantages, but at this time I tend to agree that they are mostly not worth the extra CPU cycles so I'm thinking of switching the default in the near future.

**Comment by rwwagner90** [comment]
@Turbo87 how would I go about doing that? I'm unsure how to change the settings.

**Comment by rwwagner90** [comment]
Never mind, I found it

**Comment by Turbo87** [comment]
hmm, indeed that settings dialog page isn't really documented anywhere. do you feel like opening a PR to fix that?
