### ISSUE TITLE
Support for "ember-intl"

### ISSUE THREAD

**Issue by Turbo87** [Turbo87/intellij-emberjs#77]
see https://github.com/jasonmit/ember-intl

what we could eventually do:
- translation key auto completion and referencing in templates
- "Extract translation" intention
- show translation instead of key like Android Studio

/cc @jasonmit

**Comment by jasonmit** [comment]
I love this, I want to also see how viable porting this functionality to atom will be.  Also, feel free to advertise it anywhere in the README.

**Comment by Turbo87** [comment]
implementing it is actually not that hard. the hard part is figuring out how the APIs work, if they even exist, how the ASTs/PSIs look like, etc.
