### ISSUE TITLE
Support `podModulePrefix` config option

### ISSUE THREAD

**Issue by mihaiscurtucb** [Turbo87/intellij-emberjs#79]
Granted I'm on an older version of ember and ember-cli so maybe it's a non issue, but maybe there's something i'm missing. Here is my issue:

![image](https://cloud.githubusercontent.com/assets/9959183/19640054/bcb7bbba-99e3-11e6-94ed-a542a6c4feff.png)

The component should be `ui-panel`, not `pods.components.ui-panel`.

**Comment by Turbo87** [comment]
hmm, you are using a `podsPrefix` setting, right? Haven't worked with something like that yet so it's likely that it is not supported yet.

**Comment by mihaiscurtucb** [comment]
@Turbo87 

Yes, this is in my `environment.js` file:

```
    podModulePrefix: 'app-admin-web/pods',
```

I wish i knew the first thing about Kotlin and Idea plugins so I could give you a PR 😢

**Comment by Turbo87** [comment]
> I wish i knew the first thing about Kotlin and Idea plugins so I could give you a PR 😢

Unfortunately I'm having similar problems. I do understand Kotlin but developing Idea plugins certainly isn't a well documented thing... 😕

**Comment by Turbo87** [comment]
since pods are essentially deprecated I'm not going to put any more work in on supporting them in this plugin, sorry
