### ISSUE TITLE
Plugin failed to find 'ember' executable

### ISSUE THREAD

**Issue by panthony** [Turbo87/intellij-emberjs#8]
When I try to create a new EmberJS file it fails because it cannot find 'ember':

```
08:23:51 Problem running ember-cli:
         Cannot run program "ember" (in directory "/path/to/project"): error=2, No such file or directory
```

```bash
% which ember
/opt/local/bin/ember

% ember -v
Future versions of Ember CLI will not support v4.2.1. Please update to Node 0.12 or io.js.
version: 1.13.8
node: 4.2.1
npm: 2.13.4
os: darwin x64
```

I didn't find if we could specify a path to the ember executable to use.

**Comment by Turbo87** [comment]
are you using nvm or anything like that? Otherwise my setup is mostly similar and works alright. It should be possible to create an option for choosing the ember executable though.

**Comment by panthony** [comment]
I am using nvm yes.

**Comment by Turbo87** [comment]
try starting intellij from the same command line where ember works. might be a possible workaround for now.

**Comment by panthony** [comment]
Launching the IDE using `open -a IntelliJ\ IDEA\ 15` fixed this issue but there was another crash.

I tried to create a new component using "my-component" and the process ended up with the following error:

```
Stream closed
java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at com.emberjs.cli.YesThread.run(YesThread.kt:13)
```

All files were created though.

**Comment by Turbo87** [comment]
btw there is `Tools -> Create Command-line launcher` that will create an `idea` tool that you can use right from the command line :wink: 

could you open a separate issue for that exception? that `YesThread` is just responsible for answering `y` to all questions so it might as well crash after the `ember` process itself quits. the exception should be caught though and then break out of the loop.

**Comment by panthony** [comment]
I created the new issue, thanks for the tips with "Create Command-line launcher" :+1:

**Comment by Turbo87** [comment]
I guess it would make a lot more sense to use `node_modules/.bin/ember` instead of relying on `ember` being available on the path... but even then it might fail if the wrong `node` interpreter is used...

**Comment by panthony** [comment]
It may requires a little more work but I liked the idea of having the choice to set the path to the ember executable in case the plugin is unable to discover it.

IntelliJ provides the choice to configure the executable path for almost every binary.

**Comment by nagkumar** [comment]
:53:08 PM Problem running ember-cli:
           Cannot run program "ember" (in directory "C:\temp\js\raguram"): CreateProcess error=2, The system cannot find the file specified (show balloon)


This issue is seen though ember exists in windows global path and when webstrom 11 is launched from command line ms-dos prompt which has admin privileges.

**Comment by macinjosh** [comment]
+1 on this issue.

**Comment by pongo** [comment]
window 10, webstorm 11.0.3, ember.js plugin 1.5.0

`
  Problem running ember-cli:
  Cannot run program ".\node_modules\.bin\ember": CreateProcess error=2, Не удается найти указанный файл (cannot find the file)
`

**Comment by pongo** [comment]
window 10, webstorm 11.0.3, ember.js plugin 1.5.0

I am trying to add new route 'ddd' and get error:

```
Problem running ember-cli: 
Cannot run program ".\node_modules\.bin\ember": CreateProcess error=2, Не удается найти указанный файл (cannot find the file)
```

I have ember in my project's `node_modules\.bin\`:
```
> cd .\node_modules\.bin\
> dir
 Содержимое папки C:\Users\Pavel\Documents\Ember\project-name\node_modules\.bin

08.04.2016  01:13    <DIR>          .
08.04.2016  01:13    <DIR>          ..
08.04.2016  01:13               309 ember
08.04.2016  01:13               186 ember.cmd
               2 файлов            495 байт
               2 папок  55 006 703 616 байт свободно
```

Process Monitor logs:

```
WebStorm.exe	26028	CreateFile	C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\jre\jre\bin\node_modules\.bin\ember	PATH NOT FOUND
WebStorm.exe	26028	CreateFile	C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\jre\jre\bin\node_modules\.bin\ember.exe	PATH NOT FOUND
WebStorm.exe	26028	CreateFile	C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\jre\jre\bin\node_modules\.bin\ember generate	PATH NOT FOUND
WebStorm.exe	26028	CreateFile	C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\jre\jre\bin\node_modules\.bin\ember generate.exe	PATH NOT FOUND
WebStorm.exe	26028	CreateFile	C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\jre\jre\bin\node_modules\.bin\ember generate route	PATH NOT FOUND
WebStorm.exe	26028	CreateFile	C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\jre\jre\bin\node_modules\.bin\ember generate route.exe	PATH NOT FOUND
WebStorm.exe	26028	CreateFile	C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\jre\jre\bin\node_modules\.bin\ember generate route ddd	PATH NOT FOUND
WebStorm.exe	26028	CreateFile	C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\jre\jre\bin\node_modules\.bin\ember generate route ddd.exe	PATH NOT FOUND
```

In the folder `C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\jre\jre\bin` no folder `node_modules`

**Comment by Turbo87** [comment]
@pongo thanks for reporting this. it looks like we need to use `ember.cmd` on windows instead. could you open this as a new issue so I don't forget about it?

**Comment by pongo** [comment]
@Turbo87 ok. new issue #46
