### ISSUE TITLE
Is it possible to get it to understand relative paths in styles?

### ISSUE THREAD

**Issue by kitsunde** [Turbo87/intellij-emberjs#86]
If I have  file in `./app/styles` referencing a file in `./public` it the PyCharm linter will underline it as being a nonsense path. Like say:

```css
background: url(../img/title_icons.png) no-repeat;
```

Is it possible to make it smart enough to understand it's referencing that directory?

**Comment by Turbo87** [comment]
I'm pretty sure that it is possible, but unfortunately I have no clue how to do it.
