### ISSUE TITLE
Can't import Ember projects

### ISSUE THREAD

**Issue by dwickern** [Turbo87/intellij-emberjs#99]
IntelliJ detects a "Web" project instead of "Ember.js"

git bisect blames this commit: 0945404b5d80f86ec9e192260aec7b3df2933436

(make sure to delete `.gradle` and `.sandbox` between each test)

Tested with
- IntelliJ IDEA 2016.2.5 Build #IU-162.2228.15, built on October 14, 2016
- Ember plugin version 2016.2.4-0

**Comment by Turbo87** [comment]
@dwickern I'd be very surprised if that commit was indeed responsible for breaking our code... 🤔

**Comment by dwickern** [comment]
It works if I get rid of the `<depends>` in `plugin.xml`

**Comment by dwickern** [comment]
Hmm, I think it's supposed to be just `yaml` instead of `org.jetbrains.plugins.yaml`

**Comment by Turbo87** [comment]
what are the implications of detecting a "Web" module instead? Can we "solve" that by using the FrameworkDetector instead?

**Comment by dwickern** [comment]
Here's all I see when it's imported as a Web module

<img width="356" alt="screen shot 2016-11-11 at 3 28 19 pm" src="https://cloud.githubusercontent.com/assets/752885/20233363/ac812a30-a823-11e6-9cff-502dc3af6c51.png">

**Comment by Turbo87** [comment]
😒

**Comment by Ramblurr** [comment]
I'm experiencing this as well, except the project fails to import entirely when being imported as a sub module.

It is auto-detected as type "Web", then I click finish and nothing happens, the module is not imported.

Reverting all the way back to v2016.2.1 fixes the issues.

**Comment by panthony** [comment]
Same issue here and I confirm that reverting back to `v2016.2.1` fixed the issue.

Thanks for the hint !

And keep up your awesome work, love this plugin !
